### ISSUE TITLE
Inserting templates just inserts "<++>"

### ISSUE THREAD

**Issue by CemraJC** [vim-latex/vim-latex#100]
Here's what I did:

* Installed vim-latex with vundle using the line "Plugin 'vim-latex/vim-latex'" in my .vimrc
* Added the recommended settings to my .vimrc
* Opened vim on my MSYS Git command line (windows port of linux CLI features, but everything else in vim works fine)
* Made a new text.tex file
* Attempted to apply a template with `:TTemplate`, then pressing `1`
* Observed that "<++>" was entered into the file.

Clearly, this isn't supposed to happen. Following this I attempted the following steps to rectify the issue:

1. Run the command again
    * I used `:TTemplate` and pressed `1`
    * **Result:** The "<++>" characters disappeared
    * Note that every 2nd run of the TTemplate command add/removes the "<++>" characters
2. Start with a clean .vimrc.  No change
3. Run the command as `:TTemplate article`. No change

I'm not sure where to go from here besides installing a separate vim. I would prefer not to do this and would probably just use the inferior Texmaker or something.

*Extra info:*

I'm running Windows 10, using the Git Portable (MSYS Git) installation to emulate linux on my machine. I don't use the GUI version of vim - I don't like it very much.
The output of my vim's `:ver` command is as follows:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 25 2017 09:05:56)
Included patches: 1-237
Compiled by <alexpux@gmail.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +digraphs        +folding         +langmap         -mouseshape      -mzscheme        +python3/dyn     +syntax          -toolbar         +writebackup
+arabic          +cmdline_hist    -dnd             -footer          +libcall         +mouse_dec       +netbeans_intg   +quickfix        +tag_binary      +user_commands   -X11
+autocmd         +cmdline_info    -ebcdic          +fork()          +linebreak       -mouse_gpm       +num64           +reltime         +tag_old_static  +vertsplit       -xfontset
-balloon_eval    +comments        +emacs_tags      +gettext         +lispindent      -mouse_jsbterm   +packages        +rightleft       -tag_any_white   +virtualedit     -xim
-browse          +conceal         +eval            -hangul_input    +listcmds        +mouse_netterm   +path_extra      +ruby/dyn        -tcl             +visual          -xpm
++builtin_terms  +cryptv          +ex_extra        +iconv           +localmap        +mouse_sgr       +perl/dyn        +scrollbind      +termguicolors   +visualextra     -xsmp
+byte_offset     +cscope          +extra_search    +insert_expand   -lua             -mouse_sysmouse  +persistent_undo +signs           +terminfo        +viminfo         -xterm_clipboard
+channel         +cursorbind      +farsi           +job             +menu            +mouse_urxvt     +postscript      +smartindent     +termresponse    +vreplace        -xterm_save
+cindent         +cursorshape     +file_in_path    +jumplist        +mksession       +mouse_xterm     +printer         +startuptime     +textobjects     +wildignore
-clientserver    +dialog_con      +find_in_path    +keymap          +modify_fname    +multi_byte      +profile         +statusline      +timers          +wildmenu
+clipboard       +diff            +float           +lambda          +mouse           +multi_lang      +python/dyn      -sun_workshop    +title           +windows
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2 -I/usr/include/ncursesw  -march=x86-64 -mtune=generic -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -pipe -fstack-protector -pipe -Wl,--as-needed -o vim.exe        -lm    -lncursesw -liconv -lacl -lintl   -pipe -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable
-auto-image-base -fstack-protector-strong  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt
```

**Comment by gerw** [comment]
I must admit that I do not fully understand your report. Can you show the contents of your buffer after each invocation of `TTemplate`?

**Comment by CemraJC** [comment]
Certainly! Here's a screenshot play-by-play of what happens:

**Open a new instance of vim**

![New instance (homescreen)](https://user-images.githubusercontent.com/9857188/28994205-f4d5ef90-7a0b-11e7-84d0-a72938389e51.png)

**Enter command `:e test.tex`**

![New buffer made. Buffer contents: "" i.e. empty](https://user-images.githubusercontent.com/9857188/28994208-07809974-7a0c-11e7-8a85-211016de165e.png)

**Enter command `:TTemplate` then press `1` (although the template number is irrelevant)**

![Buffer contents: "<++>"](https://user-images.githubusercontent.com/9857188/28994217-24744ddc-7a0c-11e7-8792-265a821ef193.png)

**Enter command `:TTemplate` then press `1` again**

![Buffer contents: ""  i.e. empty](https://user-images.githubusercontent.com/9857188/28994226-412077ee-7a0c-11e7-824e-98ed3f53dafe.png)

*Cycle continues for future invocations of TTemplate*

Hopefully that clears things up for you. Let me know if you need any more information.

**Comment by gerw** [comment]
This is weird. Can you enable debugging
````
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
````
and post the content of the log file afterwards?

**Comment by CemraJC** [comment]
Here's the log file: [vim-latex-suite.log](https://github.com/vim-latex/vim-latex/files/1202841/vim-latex-suite.txt)

Note that I followed the exact procedure detailed in my previous comment (with the screenshot log), except that this time I entered the commands you specified to enable debugging immediately after opening vim (before creating the test.tex buffer)

**Comment by gerw** [comment]
Thank you. It seems that vim cannot open the `article.tex` file. Does
```
:edit /c/Users/Jason Cemra/.vim/bundle/vim-latex/ftplugin/latex-suite/templates/article.tex
```
work? And
````
:0read /c/Users/Jason Cemra/.vim/bundle/vim-latex/ftplugin/latex-suite/templates/article.tex
````
?

**Comment by CemraJC** [comment]
Yes, both commands work with the following output into the buffer:
![image](https://user-images.githubusercontent.com/9857188/29001591-bdb716a8-7ad1-11e7-8da4-33bf31ebcdbf.png)

I also tried running vim with Administrator Privelages (Windows...) and that didn't seem to change anything.

Extra info: I escaped the space in the filename, so my command looked like:
`:edit /c/Users/Jason\ Cemra/.vim/bundle/vim-latex/ftplugin/latex-suite/templates/article.tex`
Just for the sake of clarity 😄

**Comment by gerw** [comment]
Thank you for your last comment! Indeed, the filename was not escaped. Now, it should work. Can you test it?

**Comment by CemraJC** [comment]
Yes! Thank you, now it works :smile:

**Comment by gerw** [comment]
Thank you for your bug report and your help with debugging (in particular the mention of the escaped space)!
