### ISSUE TITLE
I want the cursor to move when I type $$

### ISSUE THREAD

**Issue by theonlygusti** [vim-latex/vim-latex#103]
When I am in insert mode and I type `$$` the cursor doesn't move on the second keypress.

How can I prevent this behaviour?

**Comment by gerw** [comment]
I cannot reproduce. When I use the standard configuration, typing `$$` in a tex file moves the cursor between both dollar signs.

**Comment by theonlygusti** [comment]
`^` represents the cursor's position.

Each line represents a new keypress in insert mode:

```
^
$^
$^$
```

But I want it to be like:

```
^
$^
$$^
```

It's so infuriating that I can't type display maths equations without having to exit insert mode, hit `l`, then re-enter insert mode. It's the worst.

**Comment by gerw** [comment]
Yes, this is standard and desired behaviour. You should _never_ use `$$...$$` to get display math equations, see mirrors.ctan.org/info/l2tabu/english/l2tabuen.pdf, it's deadly sin #6.

**Comment by theonlygusti** [comment]
Yeah, I found out on TeX.SE today that same thing. I'm trying to use the better methods now.
