### ISSUE TITLE
vim-latex plugin has overwritten my windows mapping

### ISSUE THREAD

**Issue by porfiriopaiz** [vim-latex/vim-latex#105]
Hi \o ,

I installed vim-latex using the vim-plug plugin manager. It seems like vim-latex has overwritten my windows mapping after it was installed:

These are my windows mapping:

```
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
```

`:verbose nmap <c-j>`

Returns:
```
n  <NL>          <Plug>IMAP_JumpForward
        Last set from ~/.vim/plugged/vim-latex/plugin/imaps.vim
```
Is there any way to keep the plugin without it overwritting my windows mapping? The only one affected is `<C-j>`.

Thanks.

**Comment by gerw** [comment]
The easiest solution is to provide a mapping to `IMAP_JumpForward` in your `.vimrc`, e.g.,
`nmap <C-D> <Plug>IMAP_JumpForward`.
