### ISSUE TITLE
Error when trying to sort the bibliography

### ISSUE THREAD

**Issue by ronisbr** [vim-latex/vim-latex#107]
Hi guys!

In `\cite` autocompletion, when I use the sort option, I get this message:

```
Erro detectado ao processar function Tex_HandleBibShortcuts[40]..provider
#python3#Call:
linha   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ronan.arraes/.nvim/dein/repos/github.com/vim-latex/vim-latex/ftplugin/latex-suite/bibtools.py", line 241, in
sort
    self.bibentries.sort(cmp=cmpfun)
TypeError: 'cmp' is an invalid keyword argument for this function
```

I know this is related to python 3 as, for example, we can see here [1]. The details of my system are:

* macOS with neovim v0.2.0.
* Python 3.6.2.
* Python 2.7.10

----------
[1] https://github.com/viblo/pymunk/issues/96

**Comment by gerw** [comment]
Thank you for your bug report. Sorting was anyway broken, but should be fixed now.

Please confirm that the fix works for you.
