### ISSUE TITLE
vim-latex is not identifying correctly macOS Sierra / macOS High Sierra with neovim

### ISSUE THREAD

**Issue by ronisbr** [vim-latex/vim-latex#109]
Hi!

vim-latex uses `has('osx')` to verify if it is being running under macOS. However, this seems to not work in macOS Sierra and macOS High Sierra. The correct variable should be `has('macunix')`. If I change all the occurrences in `compiler.vim` file from the former to the latter, then everything works fine.

**Comment by ronisbr** [comment]
By the way, in vim that comes with macOS, `has('osx')` works. Is it possible to add something like `has('osx') or has('macunix')`?

**Comment by gerw** [comment]
This was changed recently due to a pull request by @congma. Maybe he can give some more details.

**Comment by congma** [comment]
Thank you. I created a simple patch (congma/vim-latex-suite@99d9f18f543641dc80650af4409fd35fdb652d8f) with your idea. I'm not sure about the relation of this repo with the `vim-latex-suite` one, but in any case, I hope this helps.

**Comment by gerw** [comment]
Thank you for the patch. I applied it also to vim-latex/master.
