### ISSUE TITLE
Incompatibility with jk and kj <ESC> mappings from the vim-easyescape plugin

### ISSUE THREAD

**Issue by rfabbri** [vim-latex/vim-latex#111]
Using http://github.com/zhou13/vim-easyescape with these options: 

```
let g:easyescape_chars = { "j": 1, "k": 1 }
let g:easyescape_timeout = 100
cnoremap jk <ESC>
cnoremap kj <ESC>
```

Won't work with vim-latex, since the IMAP will conflict.

A work-around is to modify main.vim by disabling an existing IMAP for 'k' (\kappa):
https://github.com/rfabbri/vim-latex/commit/f3102172298e7838fa2a61d1f464ed536fc733a5

Tested with VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 13 2017 04:07:30), for Mac OS,
with Python 3.

**Comment by gerw** [comment]
Similarly, you could add
```
call IUNMAP("\"`j", "tex")
call IUNMAP("\\`j", "tex")
call IUNMAP("``j", "tex")
call IUNMAP("\"`k", "tex")
call IUNMAP("\\`k", "tex")
call IUNMAP("``k", "tex")
call IUNMAP("`k", "tex")
```
to your `.vim/after/tex.vim`.

I hope this helps.

**Comment by gerw** [comment]
Does this resolve your issue?

**Comment by rfabbri** [comment]
This solves it, thanks,
but I had to use `ftplugin` in the path: `.vim/after/ftplugin/tex.vim`
