### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ArchangeGabriel** [vim-latex/vim-latex#114]
Distro packaging vim-latexsuite are packaging old versions, because they wait for stable release with version numbers ([example](https://www.archlinux.org/packages/community/any/vim-latexsuite/)).

As you’ve said recently, 1.9 is one year old, and they have been roughly 100 commits since then. Do you intend to tag new releases? :)

**Comment by tyll** [comment]
@gerw I can prepare a new release within the next days if the current state is good.

**Comment by tyll** [comment]
Which version should I use - 1.10.0?

**Comment by gerw** [comment]
Yes, the current state is ok and 1.10.0 seems to be fine. However, there are some deficiencies in the documentation. I think I could try to improve this. Afterwards, we could have a new version.

Remember that there are two version numbers: in `Makefile` and in `ftplugin/latex-suite/version.vim`.

**Comment by ArchangeGabriel** [comment]
1.10.0 is perfect per semver rules that [you seems to adhere to](https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/version.vim).

There is no urgency to release, so if @gerw wants to improve the docs first, that could be nice. ;)

**Comment by gerw** [comment]
I pushed some updates concerning the documentation (and some other minor fixes). It remains to update the credits, these seem to be extremely out-dated: http://vim-latex.sourceforge.net/documentation/latex-suite/latex-suite-credits.html.

**Comment by tyll** [comment]
Thank you for your patience. I pushed out a new release (v1.10.0) now. I will publish a new update after the credits are fixed.
