### ISSUE TITLE
\cite completion work for me with bibliography list inside the file

### ISSUE THREAD

**Issue by mikarm999** [vim-latex/vim-latex#120]
Dear Sirs, 
The \cite completion F9 does work with bibfiles, however does not work with thebibliography inside the file.
Example of the file:
********************************************
\documentclass[12pt,reqno]{amsart}

\usepackage[utf8]{inputenc}

\begin{document}
Let us start from \cite{ 
\cite{Malakhaltsev1} 

\begin{thebibliography}{99}

\bibitem{Mackenzie}
K. Mackenzie, \emph{Lie groupoids and Lie algebroids in differential geometry}, Cambridge Univ. Press, 1987.  

\bibitem{Malakhaltsev1}
M. Malakhaltsev, \emph{Foliations with leafwise structures}, J. of Math. Sci.- vol. 108, N2.- 2002.- pp. 188-210.

\end{thebibliography}
\end{document}
*************************************************************************
The debugging log file:
*************************************************************************
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : :Tex_FindBibFiles: 
view : :Tex_FindBibFiles: returning []
view : :Tex_StartCiteCompletion: No bibfiles found.
view : :Tex_SwitchToInsertMode: 
*************************************************************************
I would highly appreciate it if you could help with this problem.
Best wishes,
Mikhail Malakhaltsev

**Comment by gerw** [comment]
I confirm that this is not supported with the python-based cite-completion (and it is not compatible with this approach). Moreover, I do not see any reason for not using a bib-file.

As a workaround, you could disable
`Tex_UseCiteCompletionVer2`.

**Comment by mikarm999** [comment]
Thank you very much for the answer. 
I set  g:Tex_UseCiteCompletionVer2 = 0, and now everything (with bib-files and the bibliography inside the tex-file) works.
I suppose it would be nice to explain this in the documentation, which says 
"If a \bibliography command is not found, then Latex-Suite tries to scan the
   present file for a \begin{thebibliography} environment. If found, Latex-Suite
   searches the present file for bib-keys of the form \bibitem",
though perhaps I missed something in the explanation.
Thank you very much, again.

**Comment by gerw** [comment]
Indeed this part of the documentation was very misleading. Please check whether you agree with `:help cite` now.

**Comment by mikarm999** [comment]
Yes, now the text (:help cite) is much more clear. Thank you very much for your kind help.
