### ISSUE TITLE
potential issue with s:viewer in compiler.vim

### ISSUE THREAD

**Issue by tianzhuqiao** [vim-latex/vim-latex#122]
I install vim-latex on a Mac. When I use "\lv" to open the compiled pdf file, it shows the error message:

_Error detected while processing function Tex_ViewLatex:
Line 34:
E121: Undefined variable: s:viewer
E116: Invalid arguments for function strlen(s:viewer)
......_

It looks like the "s:viewer" variable may not always be defined in compiler.vim?

If I add the following line at the beginning of compiler.vim,  the problem goes away. 

_let s:viewer = ''"_

Thanks

**Comment by gerw** [comment]
Does the patch resolve your issue?

**Comment by tianzhuqiao** [comment]
Cool, it works now! Thanks.
