### ISSUE TITLE
Shall we make  "`w" default to "\omega"?

### ISSUE THREAD

**Issue by huangzonghao** [vim-latex/vim-latex#123]
In the main.vim file, we have

     115 call IMAP(g:Tex_Leader.'w', '\omega', 'tex')
     116 call IMAP(g:Tex_Leader.'w', '\wedge', 'tex')  " AUCTEX style

Which made me quite confused. Were the duplicates left there intentionally? But shouldn't we at least comment out one and tell users to make the changes they like in the user configuration file? Having 2 lines with one overriding another in the distribution doesn't seem to make any sense?
Or at least shall we change the order of that two command so that user would get what they expected from the default configuration?

I think this might be a mistake since in the manual it mentioned that the mapping for greek letters are provided from alpha to zeta. But currently omega is gone due to the duplicate.

**Comment by gerw** [comment]
I think we should not change the default behavior. Maybe we should add to the documentation that `` `w`` expands to `\wedge` in Section 3.5.

Note that in the beginning of Section 3, it is described how to change `` `w`` such that it expands to `\omega`.

However, I agree that we should comment out (or delete) one of these lines in `main.vim`.

**Comment by huangzonghao** [comment]
But the reference manual reads:

>  3.5 Greek Letter Mappings
> Lower case
>  ``a` through ``z` expand to` \alpha` through `\zeta`.

So I guess the original intention was to make ``w` map to `\omega` and `\o` map to `\omicron`? 

But of course we can leave the default configuration as it is now. But in this sense we should change the manual right? At least no matter which way we choose we should keep the Reference Manual and the behavior of code consistent with each other.

**Comment by gerw** [comment]
I see your point. And I am no longer convinced that we should keep the current expansion of `` `w``.

Let us dig through the history:

* The current implementation dates back to https://github.com/vim-latex/vim-latex/blame/b4ab8416eb638f95a9f45a20cdb1e463425620ff/ftplugin/latex-suite/main.vim#L116:
```vim
	call IMAP('`w', '\omega', 'tex')
	call IMAP('`w', '\wedge', 'tex')  " AUCTEX style
```
* However, in the previous commit (https://github.com/vim-latex/vim-latex/blame/f0b455b91a3082409791aa3dc3a5d734b3c6a25b/ftplugin/latex-suite/main.vim#L138), this was commented out:
```vim
	let s:greek_w = "\\omega"
	" let s:greek_w = "\\wedge"  " AUCTEX style
```

Therefore, it could be that this was an oversight. Hence, I would support you that we should delete the line which maps `` `w`` to `\wedge`. (And we should also update the documentation).
