### ISSUE TITLE
Ignores g:Tex_UseMakefile

### ISSUE THREAD

**Issue by gustaphe** [vim-latex/vim-latex#125]
Even when I have a makefile (which is basically always), vim-latex sets "makeprg=latex -interaction-mode..."
This is exactly the behaviour that g:Tex_UseMakefile is supposed to change, but it doesn't.

**Comment by gerw** [comment]
Thank you for your report. Does the pushed fix really fixes your problem?

**Comment by gustaphe** [comment]
Yes! Works like a charm.
Quick work!
