### ISSUE TITLE
Remapping some keys while using vim-latex

### ISSUE THREAD

**Issue by MahbubAlam231** [vim-latex/vim-latex#128]
I am using the plugin vim-latex/vim-latex. It's a fantastic plugin for sure. But I want some of my own mapping to be there. Say whenever I press 4 I want $$ in return with the cursor on the second $, or whenever I press { I want {} in return with the cursor on }.

Earlier I added the following to my .vimrc :
inoremap 4 $$<esc>i
inoremap { {}<esc>i

But it's not working now. What can I do to achieve similar functionality now? Thanks in advance.

**Comment by gerw** [comment]
You can do
````
call IMAP("{", "{<++>}", "tex")
call IMAP("4", "$<++>$", "tex")
````

**Comment by MahbubAlam231** [comment]
Thanks gerw. I had some other mapping too, like:
inoremap 3 <Esc>llf}i
which finds the next } whenever I press 3. I'm new to vim-latex, I'm not sure how to achieve that.

**Comment by gerw** [comment]
For this, latex-suite uses another approach: with `ctrl+j`, you can jump to the next `<++>`. That is, if you use ```
call IMAP("{", "{<++>}<++>", "tex")
```
you can use `ctrl+j` to jump out of the `{}`.

**Comment by gerw** [comment]
Did this resolve your issue?

**Comment by MahbubAlam231** [comment]
Yes. Thanks. :+1:
