### ISSUE TITLE
Forward search doesn't work with SumatraPDF

### ISSUE THREAD

**Issue by samildanach** [vim-latex/vim-latex#133]
It looks like the issue is line 384 of compiler.vim:
``let execString .= Tex_Stringformat('start %s %s -forward-search %s %s', viewer,  target_file , sourcefileFull, linenr)``

I replaced ``target_file`` with an empty string, and it began working for me
``let execString .= Tex_Stringformat('start %s %s -forward-search %s %s', viewer,  '' , sourcefileFull, linenr)``

I could submit a pull request with my changes, but I have no idea whether or not that would break something else. (Also, I've never actually submitted a pull request)

**Comment by samildanach** [comment]
I was premature in posting my 'solution' earlier.
After a a few more attempts I've reverted the line to what it was before, but added the following right before it:
``let target_file = '%:r.pdf'``
``let sourcefileFull = '%:p'``

**Comment by gerw** [comment]
What does "it does not work" mean exactly?

Can you revert to the original `compiler.vim`, enable debugging
```
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
```
(in `.vim/ftplugin/tex.vim`) and finally show the content of `vim-latex-suite.log`?

**Comment by gerw** [comment]
It is not clear why there appear two paths in the file name.

Please try to locate the log file. It should be in the working directory of the running vim instance. You can also set `g:Tex_DebugLog` to an absolute file name, if that helps.

**Comment by samildanach** [comment]
``\lv`` works just fine, opening the correct file, ``\ls`` tries to open that weirdly concatenated name.
After changing a couple lines of compiler.vim, I get ``\ls`` opening the correct file, and highlighting the correct line (not entirely sure why though)

I undid those changes  (created vim-latex-suite.log manually), hit ``\ls``,  and it wrote this:
```
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
```

**Comment by gerw** [comment]
There should be a different entry in the log file coming from https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/compiler.vim#L464.

**Comment by gerw** [comment]
What does
```
echo Tex_GetVarValue('Tex_ViewRule_pdf')
echo shellescape(Tex_GetMainFileName(':p:r') . "." . s:target, 1)
echo shellescape(expand('%:p'), 1)
```
say?

**Comment by samildanach** [comment]
my Text_ViewRule_pdf is ``sumatrapdf.exe  -inverse-search "gvim -c \":RemoteOpen +\%l \%f\""``
the second command gives me a correctly formatted filename to the appropriate pdf,
and the last command returns the filename for tex file

**Comment by gerw** [comment]
Please look again in the log file after using `\ls` and find the line beginning with `Tex_ForwardSearchLaTeX: execString = `.

**Comment by samildanach** [comment]
I think I found the correct log file, and the relevant line:
``comp : Tex_ForwardSearchLaTeX: execString = silent! !start sumatrapdf.exe  -inverse-search "gvim -c \":RemoteOpen +\%l \%f\"" 'C:/Users/Public/test.pdf' -forward-search 'C:/Users/Public/test.tex' 2``

this opened SumatraPDF with an empty document and the line
``Error load C:\Users\Public'C:Users\Public\.test.pdf'``

**Comment by gerw** [comment]
The string that is executed for calling `sumatrapdf` looks ok to me.

Are you sure that there is a `.` just in front of `test.pdf` in the error message of SumatraPDF?

I have no idea why SumatraPDF prepends the absolute path with the directory again. Maybe it is confused by the single quotes?

Does it help to set/unset `shellslash`? What is your setting for `shell`?

**Comment by samildanach** [comment]
The extraneous ``.`` was a typo.

Commenting out ``set shellslash`` from my vimrc appears to have fixed it, though!
``\ls`` works, and everything else that worked before still works.

Are there any downsides to unsetting shellslash? I have to admit, I only added it because it was in the guide

**Comment by gerw** [comment]
I think this depends on the shell which is in use, see http://vimdoc.sourceforge.net/htmldoc/options.html#'shellslash'. If you use the standard `cmd.exe`, then `shellslash` should be off. Otherwise it might help to turn it on.

Nice that it works now!
