### ISSUE TITLE
vim-latex overrides <C-j> map

### ISSUE THREAD

**Issue by jlconlin** [vim-latex/vim-latex#136]
Near the beginning of my `vimrc` file I have:

```
" Navigate vim splits like a sane person
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l
```
This gives me "better" (my opinion) movement between vim splits. 

When I load the `vim-latex` plugin (I use Vundle) then the `<c-j>` map no longer works. It doesn't matter if I'm in a LaTeX file or some other kind of file. I know it's this plugin because this problem goes away when the vim-latex plugin isn't on. 

Suggestions?

**Comment by jlconlin** [comment]
This worked. Can you please explain why?

**Comment by gerw** [comment]
Have a look at https://github.com/vim-latex/vim-latex/blob/master/plugin/imaps.vim#L591

**Comment by jlconlin** [comment]
Oh yes, of course. 👍
