### ISSUE TITLE
SmartKeyDot does not work

### ISSUE THREAD

**Issue by mikarm999** [vim-latex/vim-latex#137]
Dear Sirs, 
I'm using vim 8.1 and vim-latex 1.10.0.
Unfortunately, "..." do not expand to \ldots or \cdots.
In texrc I have TexLet g:Tex_SmartKeyDot = 1

**Comment by gerw** [comment]
What does `:imap .` says (in a tex file)?

**Comment by gerw** [comment]
This is weird.

Do you have defined a custom IMAP ending with `.`?

Do you use a recent version of latex-suite? In this case, you could try `echo IMAP_list_all('.')`. Maybe this helps to identify the issue.

**Comment by mikarm999** [comment]
Thank you very much, Gerd.
The problem was caused by my definition
:call IMAP(',.', "\\dot{<++>}<++>", 'tex')
I removed it and the normal behaviour of "..." came back.
So the case is closed.
