### ISSUE TITLE
F9 in \ref gives error and empty outline

### ISSUE THREAD

**Issue by rlouage** [vim-latex/vim-latex#143]
I use neovim and when trying to use F9 in an ref block I get some errors and an empty outline file.
I included a screenshot of the errors.

I use Windows 10 and the latest version of vimlatex.

![nvim](https://user-images.githubusercontent.com/25978762/45187144-6b206d00-b238-11e8-9071-f41aa7b68ed7.png)

**Comment by gerw** [comment]
This seems to be a python 'feature': https://stackoverflow.com/questions/47004722

What is your main file, i.e., the output of `:echo Tex_GetMainFileName(':p')`? I guess there is some `\u` inside.

Does it help if you replace line 776 in `ftplugin/latex-suite/texviewer.vim` by
```
		exec g:Tex_PythonCmd . ' retval = auxoutline.main(r"""' . mainfname . '""", """' . s:prefix . '""")'
```
 (only one additional `r` in front of `"""`)?

**Comment by rlouage** [comment]
"C:\Users\Robbe\Desktop\test.tex" is the output I get when I run the command.
If I change the line you specified everything seem to work.
Thanks for the help.
