### ISSUE TITLE
Undefined variable "v:true" in function Tex_GetMainFileName in man.vim 

### ISSUE THREAD

**Issue by maoyanjun** [vim-latex/vim-latex#149]
Operation system:windows7
vim version: gvim7.4
I install vim-latex with Bundle and put it under Vimfiles/bundle/ and add ``Bundle 'vim-latex' `` in ``_vimrc``. Then it seems work well. However, when I insert a template with ``:TTemplate`` I can get the choosen template insert into buffer but with  error messages as:
```
Error occurs when processing function <SNR>116_ReadTemplate. . Tex_pack)updateall . . Tex_GetMainFileName :
undefined variable: v:true
Invald arguments for function glob('*.latexmain',v:true) == ' '
...
....
```
I located this error in the function Tex_GetMainFileName() in main.vim, It seems this script can not use the global variable ``v:true``, I do not know whether it causes by the improper installation of vim-latex or anything else like a bug?  
Fixed it:
I just replace this variable ``v:true`` with a nonzero value as ``1``, and the script works well with no complaint.
As a vim beginner, I do not know whether it is ok to fix this problem like that. I hope for suggestions about it.

**Comment by gerw** [comment]
`v:true` was introduced in rather recent versions of vim. I have replaced it by `1`.
