### ISSUE TITLE
Hiding error output from viewer

### ISSUE THREAD

**Issue by texasflood** [vim-latex/vim-latex#15]
This isn't exactly a bug with Vim-LaTeX itself, but due to issues with evince and certain pdfs being used as figures, the following often appears all over the terminal screen:

```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
```

These can be removed with a `:redraw!`, but ideally, when VIm-LaTeX opens up an external application, e.g. evince to view the pdf output, it should pipe the error output (and stdout) to `/dev/null` or open it with `silent!` or something similar.

Also, sometimes when compiling with BibTeX, numerous errors appear on the screen in a similar fashion. These should be stopped ideally.

**Comment by gerw** [comment]
Sorry for answering so late. I cannot reproduce your problems. Can you give a more detailed description? How do you open evince?

**Comment by valentas-kurauskas** [comment]
Happens to me all the time. Something even worse happens not sure if this is related - the painted vim buffer becomes off by one line or so and editing inserts text in a wrong place. (It is repainted correctly by going up and down in the document). I use Ubuntu 16.04 and have this in my .vimrc:

```
set tabstop=4
set expandtab
set shiftwidth=4
set smartindent
set mouse=a

let g:Tex_UseMakefile=0
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_CompileRule_pdf='xelatex -synctex=1 -interaction=nonstopmode -file-line-error-style $*'
syntax on
filetype plugin on
```

**Comment by gerw** [comment]
Can you provide a precise description how to reproduce this bug? (in your settings, you do not even mention evince?)

**Comment by valentas-kurauskas** [comment]
Ok, I created you a small example based on Skippy's post in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=728678:

1. create this document:
```
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\begin{figure}
    \includegraphics{circle.pdf}
\end{figure}
\end{document}
```
2. download the figure I attached.
2. press \ll to compile then \lv to view.
3. in the pdf scroll up and down and check the vim window.

[circle.pdf](https://github.com/vim-latex/vim-latex/files/980240/circle.pdf)

**Comment by gerw** [comment]
Thank you. I can reproduce the bug by opening `evince` from `vim`. Using `gvim`, everything is fine.

**Comment by gerw** [comment]
I have pushed a commit in which the output of the viewer is redirected to `/dev/null`.

Does this resolve both of your problems?

**Comment by valentas-kurauskas** [comment]
That was quick, thank you! The error output problem is resolved for me. (The other one is rarer, I will have to see,  but it may not be latex-suite related. In any case it does not belong to this issue.)

By the way, as I switched from the Ubuntu package to the github one, I now see 2 extra windows, one for warnings and one for xetex output - is it possible to hide them by default?
