### ISSUE TITLE
Tex_RefreshFolds causes error in session

### ISSUE THREAD

**Issue by alekhe** [vim-latex/vim-latex#151]
When loading a session with TeX files, I get:

```
Error detected while processing C:/Users/*/vimfiles/pack/main/start/vim-latex-1.10.0/ftplugin/latex-suite/folding.vim:
line   10:
E227: mapping already exists for <80><fd>STex_RefreshFolds
```

In `Session.vim` I found following lines:
```
nnoremap <Plug>Tex_RefreshFolds :call MakeTexFolds(1, 1)^V^M
nmap <buffer> <silent> \rf <Plug>Tex_RefreshFolds
```
(with ^V^M being literal 0x16 and 0x1D).

However, everything seems to be working fine.

**Comment by gerw** [comment]
What is `Session.vim`?

**Comment by alekhe** [comment]
If you `:mksession` then Vim stores buffers, options, etc., in a session script file which is `Session.vim` by default. You can use it later with `vim -S`.

**Comment by gerw** [comment]
Should be fixed now. Thank you for the report.

**Comment by alekhe** [comment]
Yes, it’s fixed. Thank you.
