### ISSUE TITLE
<++> with (), {}, []

### ISSUE THREAD

**Issue by mhooreman** [vim-latex/vim-latex#152]
Hello,

With filetype=tex, when I enter ( directly followed by ), the text <++> is automatically added after the closing parenthesis.

I have the same issue with [] and {}.

The issue does not happens:
- with other filetype, including plaintex
- if I type something between the opening character and the closing one

I'm using MacVim 8.1, and my [.vimrc](https://github.com/vim-latex/vim-latex/files/2720268/vimrc.txt) is attached. I don't have any additional plugin which is described in my vimrc.

Thanks for your help.

**Comment by gerw** [comment]
It's not a bug, it's a feature: http://vim-latex.sourceforge.net/documentation/latex-suite/latex-macros.html

**Comment by mhooreman** [comment]
Oops! Thanks a lot.
