### ISSUE TITLE
Bib-Tex shortcuts does not work 

### ISSUE THREAD

**Issue by pBlasiak** [vim-latex/vim-latex#154]
Hi 
In insert mode I typed BBB but nothing happened.
My bib_latexSuite.vim file is as follows:
````vim
" File: bib_latexSuite.vim
" Author: Srinath Avadhanula
" License: Vim Charityware License
" Description:
"     This file sources the bibtex.vim file distributed as part of latex-suite.
"     That file sets up 3 maps BBB, BAS, and BBA which are easy wasy to type in
"     bibliographic entries.
"

if exists('b:suppress_latex_suite') && b:suppress_latex_suite == 1
    finish
endif

" source main.vim because we need a few functions from it.
runtime ftplugin/latex-suite/main.vim
" Disable smart-quotes because we need to enter real quotes in bib files.
runtime ftplugin/latex-suite/bibtex.vim

" vim:fdm=marker:ff=unix:noet:ts=4:sw=4:nowrap
````

Should I add something to this file to enable Bib-Tex mappings BBB etc?

**Comment by gerw** [comment]
Do you insert `BBB` in a `tex` file or in a `bib` file?

**Comment by gerw** [comment]
Of course, this should only work in bib-files.

Do the other IMAP-commands work for you (e.g., EEQ in tex-file)?

**Comment by pBlasiak** [comment]
Yes other IMAP-commands work very good.

**Comment by gerw** [comment]
What does
````
:echo IMAP_list_all('B')
````
show in a bib file?

**Comment by pBlasiak** [comment]
previously I opened firstly manuscript.tex file (I have also empty manuscript.tex.latexmain file)
secondly I opened bib file and typed BBB in insert mode and nothing happened

but now I opened firstly bib file and when I typed BBB shortcuts for bibtex work :)
so is it normal situation? I have to firstly open bib file before tex file?
