### ISSUE TITLE
Error with \lv on macOS X

### ISSUE THREAD

**Issue by Warkst** [vim-latex/vim-latex#159]
After some time searching for an offline LaTeX editor, I landed on vim-latex after finding other alternatives too slow or not vim-mode compatible. First I tried installing this plugin through Vundle, but it took me a while to figure out that that didn't install the latest version (using `\ll` from anywhere except the main file resulted in 'file not found' errors, which I was able to trace back to an outdated version thanks to the [FAQ page](http://vim-latex.sourceforge.net/index.php?subject=faq&title=FAQ#faq-compiling)).

I then downloaded and installed the plugin manually and found that `\lv` was broken, more precisely:

```
Error detected while processing function Tex_ViewLaTeX:
line   35:
E121: Undefined variable: s:viewer
E116: Invalid arguments for function strlen(s:viewer)
line   40:
E121: Undefined variable: appOpt
line   88:
E121: Undefined variable: execString
E116: Invalid arguments for function substitute(execString, '\V$*', mainfname, 'g')
line   89:
E121: Undefined variable: execString
E116: Invalid arguments for function Tex_Debug
line   91:
E121: Undefined variable: execString
```

I added `let g:Tex_ViewRule_pdf='preview'` to `~.vim/.../ftplugin/tex.vim` to fix the issue, though I thought from the [documentation](http://vim-latex.sourceforge.net/documentation/latex-suite/customizing-viewing.html) that, on mac, it was supposed to work out of the box. Perhaps there is a slight bug in `compiler.vim`?

For completeness:
Vim version: 8.1
Latex-suite: 1.10.0
macOS X: 10.14.5

**Comment by gerw** [comment]
Does it help if you add
```
let s:viewer = ''
```
after line 35 (`let s:target = target`) in compiler.vim?

**Comment by Warkst** [comment]
@gerw your suggestion fixes the issue. Want me to submit a PR?

**Comment by gerw** [comment]
This would be great!
