### ISSUE TITLE
Windows - VimtexCompileSS! shows \"'" was unexpected 

### ISSUE THREAD

**Issue by joefromct** [vim-latex/vim-latex#16]
Hi, 

I'm trying to get vimtex up and running on a windows 7 system; i believe i have all the prerequisites setup and am stumped as to why compilation doesn't work.  

I realized while reading the docs that `:VimtexCompileSS!` should compile in the foreground, and in doing so i see this error message as returned by windows cmd.exe: 

```
C:\WINDOWS\system32\cmd.exe /c (cd /D ^"C:/Users/joefromct/Documents/Templates/d   
ocument_root^" ^&^& set max_print_line=2000 ^& latexmk  -pdf -shell-escap
e  -e '$pdflatex =~ s/ / -file-line-error /' -e ^"$success_cmd = 'gvim.exe --ser
vername GVIM --remote-expr \^"vimtex#latexmk#callback^(1^)\^"'^" -e ^"$failure_c
md = 'gvim.exe --servername GVIM --remote-expr \^"vimtex#latexmk#callback^(0^)\^
"'^" ^"index.tex^")

\"'" was unexpected at this time.
shell returned 1
Hit any key to close this window...
```

I am stumped as to why this is happening.

I've attempted to deconstruct this command to find the offending single-quote but cannot seem to decipher the syntax/issue.  A simple latexmkrc works from the command line.

I have also tried adding this to my ~/.latexmkrc:  `$pdflatex = 'pdflatex -synctex=1 %O %S';` 

I'm hoping if i resolve this issue with single-shot compilation in the foreground things will work as i'm hoping. 

Any tips appreciated.  thanks, -Joe

**Comment by joefromct** [comment]
spelling

**Comment by joefromct** [comment]
Not sure if this is related to the issue, but from microsofts documentation on cmd.exe i've found the following:  [ms docs](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/cmd.mspx?mfr=true)   

> If you specify /c or /k, cmd processes the remainder of string and quotation marks are preserved only if all of the following conditions are met:
> * You do not use /s.
> * You use exactly one set of quotation marks.	
> * You do not use any special characters within the quotation marks (for example: &<>( ) @ ^ |).
> * You use one or more white-space characters within the quotation marks.	

I can see in my command issued by `:VimtexCompileSS!` there is quite a few '^' characters.. i'm trying to cobble something together to work so i can make the switch from latex-suite.

**Comment by joefromct** [comment]
I found this issue as being related and having hints:  https://github.com/lervag/vimtex/issues/40 

I tried both `set noshellslash` and `set shellslash` with no luck.

**Comment by gerw** [comment]
This is the bug tracker of the latex-suite.
