### ISSUE TITLE
E492: Not an editor command for `:RemoteOpen`?

### ISSUE THREAD

**Issue by llinfeng** [vim-latex/vim-latex#161]
I have fetched this repo using [vim-plug](https://github.com/junegunn/vim-plug) and have found [my own FIX](https://tex.stackexchange.com/a/498413/67145) to get forward searching to work (under my settings: gvim, Windows 10, native, with some slash... settings). Yet, the inverse search failed me.
![image](https://user-images.githubusercontent.com/5890407/60552390-9b238a00-9cfc-11e9-96ec-4a60201603c6.png)
I use Sumatra to view PDF and get this error when double-clicking on the page. Sumatra has the following option:
![image](https://user-images.githubusercontent.com/5890407/60552411-b1314a80-9cfc-11e9-9062-fdc5edf5be16.png)

Please advise how to get Vim to know about the `:RemoteOpen` command.

I have installed [`vimtex`](https://github.com/lervag/vimtex/), and wonder if this should add to the trouble?

**Comment by gerw** [comment]
`:RemoteOpen` is defined here: https://github.com/vim-latex/vim-latex/blob/master/plugin/remoteOpen.vim#L36

I do not have any clue why your Vim does not find this command. What happens if you invoke the command from the command line? What happens if you use
`:RemoteOpen +4 bla.txt` in vim itself?

**Comment by llinfeng** [comment]
Thank you for pointing out that I shall try to issue the `:RemoteOpen ...` command on my Vim browser directly. It has pointed me in the right direction.

I use [vim-plug](https://github.com/junegunn/vim-plug) to install the `vim-latex` package and have been restricting the `vim-latex` plugin to only work with `*.tex` files. This is done by feeding `vim-plug` with the following installation instruction:
```
Plug 'llinfeng/vim-latex', {'for': 'tex'}
```
This means that the `vim-latex` is only loaded when I am editing `*.tex` files. Thus, we have:

* In all Vim sessions that does not have to do with `*.tex` files, `vim-latex` is not sourced and `:RemoteOpen` function is not registered at all;
* For `*.tex`-editing Vim windows, for sure, I can happily issue the `:RemoteOpen` command (with its proper flags).

----

The solution to the problem above is to simply tell `vim-plug` to source the `vim-latex` plugin unconditionally. The following cleaner installation instruction solved my problem:
```
Plug 'llinfeng/vim-latex'
```
Now, `vim-latex` is sourced for all Vim sessions and I can double-click on the PDF for reverse-forwarding jumps.

Thanks again!
