### ISSUE TITLE
How to transfer commands in vimtex to vim-latex?

### ISSUE THREAD

**Issue by BerryTaylor** [vim-latex/vim-latex#162]
imap <C-f> <Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.b:vimtex.root.'/figures/"'<CR><CR>:w<CR>
nmap <C-f> : silent exec '!inkscape-figures edit "'.b:vimtex.root.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>

Command" b:vimtex.root" should be substituted by what in vim-latex? Thank you.

**Comment by gerw** [comment]
The root directory of your main tex file can be obtained by
````
Tex_GetMainFileName(':h')
````
Does it work for you?

May I ask why you want to switch from vimtex to vim-latex?

**Comment by BerryTaylor** [comment]
Thank you! I will try it soon.  Although I have partly solved my problem by using command 'PWD', it still has some bugs.  I am a student majoring both in math and economy,  which require a lot of passages written in latex, so I am just working to perfect my latex environment according to th website https://castel.dev/post/lecture-notes-2/ Unfortunately, his code on GitHub has some bugs and his latex is not as same as mine, so my work is to rewrite his code. This is where my problem comes from. jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 07/09/2019 15:38, Gerd Wachsmuth wrote: The root directory of your main tex file can be obtained by Tex_GetMainFileName(':h')
 Does it work for you? May I ask why you want to switch from vimtex to vim-latex? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
