### ISSUE TITLE
Question about how to disable the feature of auto-rephase the math symbos in vim-latex

### ISSUE THREAD

**Issue by maoyanjun** [vim-latex/vim-latex#164]
Hello, everyone. I am puzzled by the auto-rephase of the mathematical symbols with vim-latex. I want to see the origianl code that I input but every time it will rephase it and hide some notitations in Normal mode.I can only see the original one in Visual mode. For example: 
I want:
`$KK$`
but I can only get 
`KK` 
in Normal mode and the dollar symbol disappear. 
and also like that:
![93T~AG@910G} K6@R@F83Q7](https://user-images.githubusercontent.com/34297878/65045007-99c73c80-d990-11e9-8312-f6aa969a91d2.png)
It should be like:
```
\begin{equation}
    \frac{L_{P}}{L_{m}}=K \frac{D_{p}}{D_{m}} \quad \text { or } \quad N_{L}=K N_{D}
    \label{eqn:1}
\end{equation}
```
I want to know how to disable this feature and show all  noations.

**Comment by gerw** [comment]
I think that this is the conceal-'feature' of the tex syntax highlighting shipped by vim. I don't think that this is related to latex-suite.

You could try to add 
````
" No concealing in TeX
let g:tex_conceal = ""
````
to your `.vim/ftplugin/tex.vim`. This should help.

**Comment by maoyanjun** [comment]
> I think that this is the conceal-'feature' of the tex syntax highlighting shipped by vim. I don't think that this is related to latex-suite.
> 
> You could try to add
> 
> ```
> " No concealing in TeX
> let g:tex_conceal = ""
> ```
> 
> to your `.vim/ftplugin/tex.vim`. This should help.

Thanks for you reply. it works.

**Comment by gerw** [comment]
Nice to hear!
