### ISSUE TITLE
Deprecation warning imp module

### ISSUE THREAD

**Issue by royerhamn** [vim-latex/vim-latex#165]
Hi,

I get the following warning when starting gVim.
```
Error detected while processing c:/Users/runeh/vimfiles/plugged/vim-latex/ftplugin/
latex-suite/texviewer.vim:
line  714:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Press ENTER or type command to continue
```
This happened after making sure my gVim installation has python by adding to my .vimrc
`set pythonthreedll=python37.dll`

The reason for specifying the python dll above was actually to try and solve an autocomplete problem with \ref (cite was working fine).

I'm on windows10, using the latest version of vim-latex.

Any idea what might cause this? Thanks!

**Comment by gerw** [comment]
This is not a latex-suite issue. We do not import the `imp` module on line 714 (https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/texviewer.vim#L714) or anywhere else.

**Comment by royerhamn** [comment]
The issue was with Vim version, as described in /vim/vim/issues/3117.

After updating to the latest Vim patch, both this problem and my underlying problem with the \ref autocomplete are fixed.
