### ISSUE TITLE
Custom foldtext in latexmain overridden

### ISSUE THREAD

**Issue by thunktone** [vim-latex/vim-latex#166]
I have a `CustomFoldText()` function I would like to use and it works---but only if I manually source my ``latexmain'' every time I open a file. I can't figure out how to cleanly change `foldtext` from the default `TexFoldTextFunction()` without setting `g:Tex_Folding=0`.

**Comment by gerw** [comment]
It should work if you put
````
setlocal foldtext=CustomFoldText()
````
in your `.vim/after/ftplugin/tex.vim`.

**Comment by thunktone** [comment]
Thanks. I used
```vim
if exists("*CustomFoldText")
    setlocal foldtext=CustomFoldText()
endif
```
in `.vim/after/ftplugin/tex.vim` as the function is project specific.
