### ISSUE TITLE
Error message in docs when modelineexpr is off

### ISSUE THREAD

**Issue by kstarsinic** [vim-latex/vim-latex#167]
When modelineexpr is off (the default), I get this error message when I view the latex-suite help (e.g., ":help latex-suite.txt"):

`E992: Not allowed in a modeline when 'modelineexpr' is off: foldtext=substitute(v:folddashes.substitute(getline(v:foldstart),'\\s*\\
*.*',"",""),'^--','\ \ \ \ \ \ ','')`

**Comment by gerw** [comment]
Thank you for reporting!
