### ISSUE TITLE
Allow R chunk folding in .Rnw files

### ISSUE THREAD

**Issue by earcanal** [vim-latex/vim-latex#168]
`.Rnw` files are a mixture of LaTeX and R. R chunks are parsed by `knitr` and look like this:

```
<< ... >>=
R code
...
@
```

It would be nice to be able to tag these for folding during `\rw`. It looks like this could be implemented with a relatively small change to `folding.vim`, by someone with enough experience to do this without breaking the LaTeX folding.

**Comment by gerw** [comment]
You can use
````
call AddSyntaxFoldItem ( '^<<.*>>=', '^@', 0, 0)
call MakeSyntaxFolds(1)
````

This is, however not persistent, you have to redo these steps after `\rf`. Or you edit folding.vim...
