### ISSUE TITLE
Compiling with warning hides the original edited file's buffer

### ISSUE THREAD

**Issue by arbolis** [vim-latex/vim-latex#169]
I am not sure if this is intended, but when I compile a file.tex and there are warnings, there is the quickfix window and the log window that get prompted, but they occupy the whole screen, I cannot see the document I was editing anymore. 
I have to manually type :bfirst to get back the to original document's buffer, which is quite annoying to say the least. 
I could also do :ball to show the 3 buffers at once, which I think should be the default, so one can see the edited document, the quickfix window as well as the log window at once.
Am I missing something?

**Comment by gerw** [comment]
I cannot reproduce. I have a vim session with only one window. If I issue compiling with `\ll` and we have an error, then I get three windows (original one, quickfix list, log file).

Please give some more detailed instruction how your error can be reproduced.

**Comment by arbolis** [comment]
I am a bit baffled, I am unable to reproduce it for now, it works fine now! Very strange...!
