### ISSUE TITLE
There is no README.md

### ISSUE THREAD

**Issue by lindhe** [vim-latex/vim-latex#17]
I have no idea what this project is about, exept guessing by the name.

**Comment by eduOS** [comment]
I'm wondering if I can just install vim-latexsuite by retrieving this repo from Git to bundle under the $HOME/.vim directory. I'm a novice to latex and hope that you could give me the pointer of how to install this plugin from this source as a submodule under the version control of Git. 

Thanks.

**Comment by eduOS** [comment]
PS: I've installed it in my Ubuntu using this line: `sodu apt-get install vim-latesuite`

**Comment by chantisnake** [comment]
Here it is:

http://vim-latex.sourceforge.net/
