### ISSUE TITLE
Passing arguments to Bibtex in Git Bash for Windows

### ISSUE THREAD

**Issue by DaanVel** [vim-latex/vim-latex#179]
My current Latex workflow involves using Mendeley to automatically create .bib files. These bibfiles are stored in a Mendeley directory in my home folder. Because I don't want to have all my projects in this folder, I used to have the following bibtex command in TeXstudio
```bibtex --include-directory="C:\Users\xxx\Mendeley" %```. Recently I have installed Git for windows, and since I liked the Git Bash, have been toying around with Vim and the Vim-Latex suite. Having seen it for a while, I want to start using it for production work.

In my .vimrc file I tried to set up bibtex as such (probably should use ftplugin file for this)
```.vimrc
let g:Tex_CompileRule_bib='bibtex --include-directory="C:\Users\xxx\Mendeley" $*'
```
I feel like I have used every combination of escaping the "", using Windows/Unix file path and expressions that should expand to the filename. But my bibtex.log keeps showing this:
```
2020-06-01 11:27:41,404+0200 INFO  bibtex - this process (13648) started by 'bash' with command line: "C:\Program Files\MiKTeX 2.9a\miktex\bin\x64\bibtex.exe" Report
2020-06-01 11:27:41,442+0200 INFO  bibtex - this process (13648) finishes with exit code 1
```
i.e. The ```--include-directory``` argument does not get passed to Bibtex. Similar .vimrc definitions like ```let g:Tex_ViewRule_dvi='yap -1 -s ""'``` do manage to pass their arguments. Is there anything I am doing wrong?

**Comment by gerw** [comment]
One solution would be to use the `$BIBINPUTS` variable (in Git Bash).

Otherwise, you could try to enable debugging (of latex-suite) and to look into the log file:
````
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
````
