### ISSUE TITLE
Default compile and view rules don't handle file names with spaces

### ISSUE THREAD

**Issue by BessieTheCow** [vim-latex/vim-latex#184]
The default compile and view rules don't enclose the file name in quotes, so if a file name includes spaces it gets interpreted as separate arguments by the shell. A workaround is to set the compile and view rules in `~/.vimrc` and add quotes to the file name.

**Comment by gerw** [comment]
What exactly do you mean? The compile rules in `texrc`? If you like, you could post your workaround rules and I can incorporate them.

**Comment by BessieTheCow** [comment]
Yes, the compile rules in the `texrc`. We would change `g:TexCompileRule_pdf` to `'pdflatex -synctex=1 -interaction=nonstopmode -file-line-error-style "$*"', and similarly for the other rules. I just made PR #185 to do this. For the view rules, the plugin appends the file name without quotes to the compile rule, so I'm guessing the code that does this needs to be changed to add quotes around the file names. The workaround for that which I'm using right now is `let g:Tex_ViewRuleComplete_pdf = 'xdg-open "$*.pdf"'`

**Comment by gerw** [comment]
I merged your pull request, thank you!
