### ISSUE TITLE
When I use vim-latex's F9 bibkey completion key to find matches for my citations I am getting "E121: Undefined variable: foundCiteFile"

### ISSUE THREAD

**Issue by CptMoroni** [vim-latex/vim-latex#186]
I don't know how to provide a minimum working example, because this was working before on these files.  What *has* changed is that I updated to the latest version of Vim and moved my latex-suite installation to the new pack directory.  

---

Much of vim-latex seems to work, but <kbd>F9</kbd> no longer works, instead several errors pop up, the first error statement is, 

    Error detected while processing function Tex_Complete[90]...Tex_GrepHelper[19]..Tex_ScanFileForCite: line 82:

After that there follow several instances of the error code

    E121: Undefined variable: foundCiteFile  

Then the final error that I see is 

    No bibkey, label or word beginning with 'partial_bibkey'

where I have substituted my partial bibkey with `partial_bibkey`.

---

Since BibTeX can find the files when I run it on the LaTeX file, I don't think that there is an issue with the setup, but something is wrong.  Can anyone give me some guidance on how to troubleshoot this?

Thanks!

**Comment by gerw** [comment]
I have initialized an uninitialized variable. Does this fix your problem? If not, please post a MWE.
