### ISSUE TITLE
How to forbid Quickfix and log windows popup?

### ISSUE THREAD

**Issue by ucasFL** [vim-latex/vim-latex#187]
![Screenshot from 2020-11-11 14-27-43](https://user-images.githubusercontent.com/22127746/98776564-200ecf80-242a-11eb-89b9-124a0e7f14eb.png)
Hi, is there any options to forbid these two windows popup, I didn't find in documents. Thanks very much!

**Comment by gerw** [comment]
Can you give a more precise description? What do you have done?

**Comment by ucasFL** [comment]
> Can you give a more precise description? What do you have done?

When compile finished, these two windows popup, so i have to close them with `CTRL-WO`, i don't want them popup.

**Comment by gerw** [comment]
The preview window can be disabled by the variable `Tex_ShowErrorContext`. It is currently not possible to disable the quickfix window.

**Comment by ucasFL** [comment]
Ok, thank you!
