### ISSUE TITLE
Fold Markers fold at wrong level

### ISSUE THREAD

**Issue by folofjc** [vim-latex/vim-latex#188]
Though the documentation is ambiguous, it seems like the fold markers <<< and >>> are folding at the wrong level. I would expect that these would fold at the lowest level, like an item, etc. However, they fold at least at the subsection level. Which means that if you have the markers inside a subsection and then try to fold the subsection, it will fold down until the >>> marker, which is wrong. Then after this marker, you cannot fold the subsection anymore, since it is already folded. These markers should always fold from one to the next. Here are two MWEs, the first with just sections and subsections, and the second with the fold markers inside a subsection. (change filetype to .tex)

[MWE_sects.txt](https://github.com/vim-latex/vim-latex/files/5580287/MWE_sects.txt)
[MWE_sects_w_markers.txt](https://github.com/vim-latex/vim-latex/files/5580288/MWE_sects_w_markers.txt)

**Comment by folofjc** [comment]
Okay, I looked in the code and indeed the fold markers are at the very bottom, after sections. I moved this part up to where I want it. Perhaps it was designed this way. In any case, I that something in the documentation on folding that lists the order or commands, environments, sections, comments, etc would be helpful.

**Comment by folofjc** [comment]
Okay, I saw that in the call to Tex_FoldSections that <<< is also sent as an ending pattern. So I guess it was designed that the markers end a section. I removed that pattern and it does what I would expect, now. 

Just to reiterate, if it is not meant to do what I thought it would, then perhaps some more explanation in the docs would be helpful.

**Comment by gerw** [comment]
Thank you for spotting this inconsistency. I have removed '<<<' as an ending pattern for sections. Do you think it is ok now?

**Comment by folofjc** [comment]
I think so, I haven't tried this one, but that is what I did. I also moved the marker fold above the section fold to make sure it happened first. I am using the source-forge version (with a couple changes for myself that I have been too lazy to move into a separate location). But I only found this because of another problem I was having, so I'll make another issue. Thanks for the quick response!
