### ISSUE TITLE
Fold command

### ISSUE THREAD

**Issue by folofjc** [vim-latex/vim-latex#189]
The documentation is clear that folding commands is difficult due to the unfinished curly braces problem. It states that if there is another command with curly braces on the same line that starts a command, then it will not be folded. However, what is not stated is that in the case where there is a command _within_ the fold, the fold will stop at the first `}` that it sees. So the folding of commands only works if there are no other curly braces anywhere within the command. (As a work around, I am using the fold markers `<<<` and `>>>` to fold commands; This is why I noticed #188).

I understand that it is a tough bug to solve, so maybe the only solution is to update the docs with this additional caveat.

**Comment by gerw** [comment]
Indeed, this is almost impossible to fix. (I also did not used folding of commands myself)
