### ISSUE TITLE
Marks the file above as a tex file

### ISSUE THREAD

**Issue by dncnmcdougall** [vim-latex/vim-latex#191]
First this is an amazing pluging and I am sure I only use one iota of what it is capable of. But I do use that iota often.

I have recently (the last 6 months) encountered a bug which is fairly harmless but very irritating:
when I open a tex file for the first time in the bottom window of a horizontal split it sets its filetype correctly to tex but does not have syntax highligting applied. Additionally the top file in the split gets its filetype set to tex and syntax highlighted.

To reporduce:
create files a.txt, b.md and c.tex in a folder.
`vim a.txt` -- Note that ft=text
`:botright split b.md` -- Note that ft=markdown
`:botright split c.tex` -- Note that ft=tex, but that the syntax is not applied. Note also that a.txt now has ft=tex.

Note that if the file was previously opend then it maintans correct highlighting and does not cause other files to have their filetype set.

I am happy to have a look at this, but thought I would first ask for comment on the issue.
Is this reproducable? Is it easy? 
What are the coding guidlines I should respect when contributing to this?

Thank you

**Comment by gerw** [comment]
I cannot reproduce this issue. Latex suite itself does not set the filetype or enables the syntax highlighting. This is typically done in the '.vimrc' file. Hence, this might be a problem in your configuration files itself.

**Comment by dncnmcdougall** [comment]
OK thank you.
I have stripped down my vimrc file. Note that I am using neovim.
I have invesitgated further:
The problem does not occur if:
I stop using vim-latex
I do use vim-latex but don't set `splitright`

Also the effect is most prominent when there is an environment in the text file:
If there is no envronment in the tex then the syntax is applied to the top file, but the filetype is correct.
If there is an environment then the filetype of the top file is changed. I don't understand!

I am  using 
`nvim a.txt +":botright split b.md" +":botright split c.tex"`
The content of all three files is the same:
> * Hello
> \latex
>\begin{cat}
>   the cat
> \end{cat}

**Comment by gerw** [comment]
I still cannot reproduce. Can you try it with the regular vim? Maybe it is a problem in nvim?

**Comment by dncnmcdougall** [comment]
I have used a plain vim ( thank you for the  suggestion) version 8.1

As it is not my commonly used editor it is minimal. In my .vim folder I copied vim-latex.
And my entire vimrc is:
> filetype plugin indent on
> syntax on
> splitright

**Comment by gerw** [comment]
Does the bug still occur?

**Comment by gerw** [comment]
Ok, now I am able to reproduce a similar bug. Just to be sure: If the bug occurs, is the filetype in the three windows set correctly? For me, the filetype is correct but some window may show a wrong syntax highlighting (e.g. the text-window has tex-highlight).

**Comment by dncnmcdougall** [comment]
Yes that is what I see too.
Also note that the cursor ends in the wrong buffer after the split, namely in b.md.

**Comment by gerw** [comment]
A very strange bug.

Which commands are actually affected by 'splitright'? Mainly 'vsplit' and 'vnew'?

**Comment by gerw** [comment]
I think I have pinned the issue down: If I have three vertical splits where the middle one is focused, then the result of ":q" depends on "splitright". If it is on, the top window gets the focus, otherwise the bottom one. This seems to be a bug in vim.

**Comment by dncnmcdougall** [comment]
I would only expect vsplit to be affected bt splitright, so it is very weird indeed and probably a bug in vim.
It does raise the interesting question, though, why this incorect syntax highlighting happens for vim-latex and not (as in our example) markdown or other file types.

**Comment by gerw** [comment]
Yes, this seems to be a bug in vim, see https://github.com/vim/vim/issues/7721.

While opening a tex file, latex suite tries to do some magic which involves splitting (`:split`) and closing (`:q`) of windows. And if the cursor ends up in the wrong window afterwards, vim seems to apply the syntax highlighting to the wrong window.

**Comment by dncnmcdougall** [comment]
Thank you. I think we can close this issue.
Is there a quick work around that does not involve turing off splitright?
Perhaps diabling some vim-latex features?

**Comment by gerw** [comment]
Yes, I think
````
let g:Tex_PackagesMenu = 0
````
should help.

**Comment by dncnmcdougall** [comment]
Excellent that did it, thank you.
