### ISSUE TITLE
E117: Unknown function: IMAP 

### ISSUE THREAD

**Issue by x21L** [vim-latex/vim-latex#192]
I freshly installed Vim and vim-latex on Windows 10. I used Vundle and when opening a TeX file I am always getting those Errors
`E117: Unknown function: IMAP `. 

I am using gVim 8.2.2434

**Comment by gerw** [comment]
This function is defined in https://github.com/vim-latex/vim-latex/blob/master/plugin/imaps.vim#L158.

This seems to be an error in your configuration.

**Comment by x21L** [comment]
What can be wrong with my config if I am using a plugin manager and a fresh install?

**Comment by gerw** [comment]
I don't know. Does vundle set up your runtimepath in the correct way? Do you have the `imaps.vim` file? Is it loaded?

**Comment by x21L** [comment]
Yes I do have the file. No it is not loaded. 

I will try an install without vundle. thank you for your help

**Comment by thedoctar** [comment]
I fixed this by adding the following line in bib_latexSuite.vim:
```

" source imap.vim because we need a few functions from it.
runtime plugin/imaps.vim
```
