### ISSUE TITLE
auto compiling multiple times does not work

### ISSUE THREAD

**Issue by kadlecf** [vim-latex/vim-latex#196]
There appears to be a bug in the multiple compilation procedure using BibTeX.

My current version of the latex suite is the one included in the Linux OpenSUSE Tumbleweed
distribution; the Technical data reads:

~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ 
 		Installed Version
Version:	20120125-39.5
Build Time:	Tue 09 Mar 2021 08:29:59 CET
Install Time:	Wed 17 Mar 2021 15:59:07 CET
License:	Vim
Installed Size:	788.1 KiB
Download Size:	0 B
Distribution:	openSUSE Tumbleweed
Vendor:		openSUSE
Packager:	https://bugs.opensuse.org
Architecture:	noarch
Build Host:	old-atreju5
URL:		http://www.vim.org/
Source Package:	vim-plugins-7.3.0-39.5
Media No.:	0
~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ - ~ 

I have been using the latex-suite for years, and it used to work well as for
BibTeX compilation (I can make no statements about the makeindex). The algorithm
for multiple compilation is outlined in the latex-suite manual, see

:help compiling-multiple

In brief, when the .aux file changes because a new \cite command was added to
the .tex source, or because some \cite commands were permuted, the compilation
via \ll should automatically run BibTeX, and rerun LaTeX up to twice in order to
get all the citation correctly. This has stopped working in the course of
updates, presumably because of a higher version of vim (?).

According to my enquiries within the code, there seems to be a problem in
main.vim. The call of the function 

  call Tex_GotoTempFile()

appears to split to a temporary file; however, the split window is in a
different directory (/tmp/...) , and apparently this one becomes the current
directory. Then, the code is not able to find the .aux file, since it is
assuming it in the current directory.

The solution I found consists in adding the line:

  exe 'cd '.s:origdir

after each call of 

  call Tex_GotoTempFile()

. It would be worth checking whether this is a correct solution, and what
happens with the .idx files / makeindex.

**Comment by gerw** [comment]
For me it seems to work fine. Can you post a MWE?

And some debug output after `\ll`?

````vim
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
````

**Comment by gerw** [comment]
Which version of vim do you use?

**Comment by kadlecf** [comment]
:version
VIM - Vi IMproved 8.2 (2019 Dec 12)
Included patches: 1-2607
Compiled by 'http://www.opensuse.org/'
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +cursorshape       +job               +mouse_urxvt       +signs             +vartabs
+arabic            +dialog_con_gui    +jumplist          +mouse_xterm       +smartindent       +vertsplit
+autocmd           +diff              +keymap            +multi_byte        -sound             +virtualedit
+autochdir         +digraphs          +lambda            +multi_lang        +spell             +visual
-autoservername    +dnd               +langmap           -mzscheme          +startuptime       +visualextra
+balloon_eval      -ebcdic            +libcall           +netbeans_intg     +statusline        +viminfo
+balloon_eval_term +emacs_tags        +linebreak         +num64             -sun_workshop      +vreplace
+browse            +eval              +lispindent        +packages          +syntax            +wildignore
++builtin_terms    +ex_extra          +listcmds          +path_extra        +tag_binary        +wildmenu
+byte_offset       +extra_search      +localmap          +perl              -tag_old_static    +windows
+channel           -farsi             +lua/dyn           +persistent_undo   -tag_any_white     +writebackup
+cindent           +file_in_path      +menu              +popupwin          -tcl               +X11
+clientserver      +find_in_path      +mksession         +postscript        +termguicolors     -xfontset
+clipboard         +float             +modify_fname      +printer           +terminal          +xim
+cmdline_compl     +folding           +mouse             +profile           +terminfo          -xpm
+cmdline_hist      -footer            +mouseshape        -python            +termresponse      +xsmp_interact
+cmdline_info      +fork()            +mouse_dec         +python3/dyn       +textobjects       +xterm_clipboard
+comments          +gettext           +mouse_gpm         +quickfix          +textprop          -xterm_save
+conceal           -hangul_input      -mouse_jsbterm     +reltime           +timers
+cryptv            +iconv             +mouse_netterm     +rightleft         +title
+cscope            +insert_expand     +mouse_sgr         +ruby/dyn          +toolbar
+cursorbind        +ipv6              -mouse_sysmouse    +scrollbind        +user_commands
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "\~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib
-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libmount -I/usr/include/blkid -
I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-
pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/wayland -I/usr/include/libxkbcommon -I/usr/include/atk-1.0 -I/usr/include/at
-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread -O2 -Wall -fstack-protector
-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -Wall -pipe -fno-s
trict-aliasing -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L. -flto=auto -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32.0/x86_64-
linux-thread-multi/CORE -flto=auto -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz
 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lSM -lICE -lm -lseli
nux -ltinfo -lacl -lgpm -ldl -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32.0/x86_64-linux-thread-multi/CORE -L/usr/local/lib64 -fstack-pro
tector-strong -L/usr/lib/perl5/5.32.0/x86_64-linux-thread-multi/CORE -lperl -lm -ldl -lcrypt -lpthread

**Comment by kadlecf** [comment]
Here is the minimum non-working example.

\documentclass{article}

\begin{document}

 Ref.~\cite{foo}

\bibliographystyle{unsort}
\bibliography{biblist.bib}

\end{document}

= = =
At the very first compilation, LaTeX was run 2 times. The .aux file produced does contain a bibdata line:

\bibdata{biblist.bib}

Despite that, bibtex is never triggered, whatever I write instead of "foo" (there is no .blg file produced). But it should be run always, as the documentation says:

4. If the .aux file generated by the latex compiler contains a \bibdata line,
   then it means that we are using a .bib file. Therefore, run bibtex.
   
   NOTE: This means that we will always run bibtex whenever we use the
         \bibliography command whether or not we actually need to. At this time,
         Latex-Suite does not parse the .aux file before and after the latex
         compiler to see if we are required to rerun bibtex.

= = =
Indeed, when I applied my "patch" (exe 'cd '.s:origdir, see the first post above), bibtex was run always.

When I issue commands
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"

the file vim-latex-suite.log reads as follows:

comp : +Tex_RunLaTeX, b:fragmentFile = 0
comp : Tex_RunLaTeX: compiling to target [pdf]
comp : Tex_RunLaTeX: getting dependency chain = [pdf]
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : Tex_RunLaTeX: setting target to pdf
comp : Tex_RunLaTeX: compiling file multiple times via Tex_CompileMultipleTimes
comp : Tex_CompileMultipleTimes: latex run number : 1
comp : Tex_CompileLatex: getting mainfname = [MWE-bib.tex] from Tex_GetMainFileName
comp : Tex_CompileLatex: execing [make! MWE-bib.tex]
comp : Tex_CompileMultipleTimes: errors = []
comp : Tex_CompileMultipleTimes: Ran latex 1 time(s)
comp : Tex_RunLaTeX: errlist = [
 1:  ]
comp : Tex_SetupErrorWindow: mfnlog = MWE-bib.log
comp : -Tex_RunLaTeX

= = =
Here is the entire section concerning the vim-latex-plugin from my ~/.vimrc.

"- - - - - - - - - - - - - - - - - - - - - - - - -
" rules for vim-latex-plugin
" open keyword help by shift-F1:
autocmd BufEnter *.tex map <S-F1> evbh"ty:let @t = substitute(@t, '{', '', '')<CR>q:ih <ESC>"tp<CR>
autocmd BufEnter *.tex inoremap '/ \parallel 
set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat='pdf'                             
let g:Tex_MultipleCompileFormats='pdf'                             
let g:Tex_ViewRule_pdf = 'okular --unique'                                 
let g:Tex_CompileRule_pdf = 'pdflatex -synctex=1 -interaction=nonstopmode -file-line-error $* -inverse-search "gvim --servername GVIM --remote +\%l \%f"'
let g:tex_IgnoredWarnings = 
    \'Underfull'."\n".
    \'Overfull'."\n".
    \'specifier changed to'."\n".
    \'You have requested'."\n".
    \'Missing number, treated as zero.'."\n".
    \'There were undefined references'."\n".
    \'Citation %.%# undefined'."\n".
    \'LaTeX Warning:'."\n"
let g:Tex_IgnoreLevel = 8
"pressing \lw writes and compiles:
:nnoremap <Leader>lw :up!<cr>:call Tex_RunLaTeX()<cr>
"in insert mode, insert item:
imap <Leader>ii <Plug>Tex_InsertItemOnThisLine
au VimEnter * au FileType tex silent! unmap! <buffer> é
"- - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by gerw** [comment]
I still cannot reproduce.

Btw: Your vim has python support, hence, `Tex_GotoTempFile` should not be used (see `main.vim`).

What does
````vim
echo Tex_UsePython()
````
say?

**Comment by kadlecf** [comment]
Weird. When I type

:echo Tex_UsePython()

I get

E117: Unknown function: Tex_UsePython

As you say, the feature
+python3/dyn
seems to be active.

**Comment by gerw** [comment]
Did you try this command in a tex file, i.e., in a situation where latex-suite is loaded?

**Comment by kadlecf** [comment]
Yes, and even after the compilation via \ll.

**Comment by gerw** [comment]
Then you have a very old version of latex-suite installed. This function has been introduced 6 years ago: https://github.com/vim-latex/vim-latex/blame/master/ftplugin/latex-suite/main.vim#L949

**Comment by kadlecf** [comment]
This is well possible; the latex suite version comes from the distribution. I wonder how I can identify the version?

**Comment by kadlecf** [comment]
Thank you. In my case, it says:

Latex-Suite: version 1.8.23

On GitHub, it is at least 1.10.1, as i infer from
https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/version.vim

I have already initiated an update in the distribution, which I will try to commit there (with someone's help). Hopefully this will resolve the issue.
