### ISSUE TITLE
Cannot fold new environment

### ISSUE THREAD

**Issue by radovan-urban** [vim-latex/vim-latex#198]
I have set up folding for frame environment. I can edit individual slides using za or zo. When done editing I can similarly close them with either za or zc.

However, when I create a new frame, I cannot close it! I gotta close and reopen document to close the new fold. After that it works as expected.

macOS Catalina; MacVim 8.2 (via macports); vim-latex 1.10.0 (manual install).

**Comment by gerw** [comment]
You have to re-fold the document via `\rf`, see http://vim-latex.sourceforge.net/documentation/latex-suite/latex-folding.html.

**Comment by radovan-urban** [comment]
I do not know how I missed it!  Thank you!
