### ISSUE TITLE
Moving to next <++> unfolds too many folds

### ISSUE THREAD

**Issue by albinahlback** [vim-latex/vim-latex#201]
```latex
[Here is cursor]
\begin{document}
\section{First}
Some text.

\section{Second}
Some text.

\section{Third}
\subsection{Subsection}
\begin{equation*}
  f(x) = \sin(x)
\end{equation*}

\begin{equation*}
  a^2 + b^2 = c^2
\end{equation*}

\begin{equation*}
  E = m c^2 
\end{equation*}
<++>

\end{document}
```
With everything folded, clicking `<C-J>` here unfolds every fold in the third section, while only needing to open the fold for section "Third" and the subsection "Subsection".

**Comment by gerw** [comment]
This seems to be a bug/feature of `:foldopen!`, which is used in https://github.com/vim-latex/vim-latex/blob/master/plugin/imaps.vim#L516.

If you replace this line by `normal zv`, it should work as you expect. If it works for you, I will patch it.

**Comment by albinahlback** [comment]
Works perfect!

**Comment by gerw** [comment]
Ok, I pushed it.
