### ISSUE TITLE
Question: Bug tracking in syntax for my local branch of vim-latex -- how do I do it?

### ISSUE THREAD

**Issue by albinahlback** [vim-latex/vim-latex#202]
Just as a note, this bug does not appear in the official `vim-latex`. If this is not fitting here, feel free to remove this.

I have my own local branch of `vim-latex`, whose main purpose is for me to add some useful shortcuts and functions.

A problem I have is for some long file like
```latex
text
\begin{gather*}
  a = b
\end{gather*}
following text
\begin{gather*}
  c = d
\end{gather*}
```
When having the `gather*`-environments folded, and adding some math before this (such as `$x = y$`), the syntax after the fold changes to math-syntax (i.e. the color of the text changes). If I then open the first `gather*`-fold, the syntax for the following text corrects itself, but the problem instead shifts to the next fold (and so on).

This is not specific for `gather*`-environments.

I would like to track this bug, but how can I do it? I have tried to do stuff like `git diff myownrepository/master..vimlatex/master` just to check if I have done anything weird to my branch, but I haven't found anything that can contribute to this behaviour.

Edit: I was able to reproduce it, and thus I will close this one and open another issue regarding it.

**Comment by gerw** [comment]
One possibility to hunt down such a bug is `git bisect`. It allows you to find the patch which introduced this bug.
