### ISSUE TITLE
Compiler/Viewer target setting per file/project

### ISSUE THREAD

**Issue by easior** [vim-latex/vim-latex#204]
LaTeX-suite provides the option g:Tex_DefaultTargetFormat for default
compiler/viewer target. This option is inconvenient for those users with
multiple TeX engines or many TeX files/projects. For instance,
g:Tex_DefaultTargetFormat is set to DVI, if there is only one other TeX file
using XeLaTeX, it's acceptable. But if there are many TeX files, some using
XeLaTeX engine, other legacies using LaTeX engine. Every time I compile those
files of the former type, I should use :TTarget/:TCTarget/:TVTarget several times.
It's on the same situation by adapting g:Tex_DefaultTargetFormat.

In Vim Editor, some settings could be passed by Vim modelines. I tried to put the following line
`% vim: let g:Tex_DefaultTargetFormat='pdf' :`
or 
`% vim: TTarget pdf :`
into some specific files. Vim complained that something wrong happened in those modelines
while those files were opened. I didn't try to put that line into latexmaintex file.

Is it possible to achieve such setting per file/project?

**Comment by gerw** [comment]
Yes, such settings can be dropped in the `.latexmain`-file, see http://vim-latex.sourceforge.net/documentation/latex-suite.html#latex-project-settings.

**Comment by easior** [comment]
Wow, it's great and flexible. Now `g:Tex_DefaultTargetFormat`, `g:Tex_FormatDependency_*` could be used for separate LaTeX file/project in .latexmain file.
