### ISSUE TITLE
Reverse/hanging indentation for certain expressions

### ISSUE THREAD

**Issue by albinahlback** [vim-latex/vim-latex#209]
I find it easier to read a hanging indentation for certain expression within mathematical environments, such as:
```latex
\begin{gather*}
  f(x)
\;=\;
  x^{2}
\tx{.}
\end{gather*}
```
Therefore I ask if there is a way to achieve this, instead of having to resort to manual indentation? (It is actually a real pain since if I write `\;=\;` without indentation, I have to manually indent `x^`, and then after typing one more `^`, IMAP is called which resets the indentation to the line above.)

**Comment by albinahlback** [comment]
One alternative seems to be to set `gather` to an itemize environment with no indentation and setting `\;=\;` to an item, where `g:tex_indent_items = 1`. But with this solution, I have problems with double indentation when inserting a new line below `\begin{gather*}`. I also would like `g:tex_indent_items` to be unset, so that also poses a problem.

**Comment by gerw** [comment]
This should work:
````
let g:tex_indent_items = 1
let g:tex_itemize_env = 'i_will_not_match'
let g:tex_items = '\\,=\\,'
````

**Comment by gerw** [comment]
Which problem? Note that I did not set `gather*` to be in `tex_itemize_env`.

**Comment by albinahlback** [comment]
Ahhh, sorry. Thank you so much!
