### ISSUE TITLE
Inserting citation with dash fails

### ISSUE THREAD

**Issue by albinahlback** [vim-latex/vim-latex#210]
Using F9 to include something like `@article{dhoker-duke,` fails to insert the citation from a `bib` file. In `texviewer.vim`, I end up in the lines containing
```
					call Tex_GrepHelper(s:prefix, 'bib')
					redraw!
					call <SID>Tex_SetupCWindow()
```

Let me know if anything else is needed.

**Comment by gerw** [comment]
Does it help if you replace the second `\w` on https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/texviewer.vim#L384 by `.`?

Anyway, it seems that you use the old cite-completion. If your vim is compiled with python support, you should set `Tex_UseCiteCompletionVer2` to `1` to enable the "new" interface.
