### ISSUE TITLE
Recent upgrade breaks pdf view

### ISSUE THREAD

**Issue by a-figment** [vim-latex/vim-latex#217]
Recently upgraded vim-latex with plug and have since been experiencing troubles with pdf output. Previously I've only `zathura`, but `mupdf` has many of the same problems.

1. Viewing location reset. All `mupdf` instances (including those generated by vimlatex) are reloaded upon updating a .tex file (for the first time in a session).  e.g. two pdfs open, one by vimlatex and some other pdf. Editing the .tex file and saving `:w`, will force all `mupdf` instances to reset, making the current display page start at page 1.
2. Slow update time. Even for small .tex files, saving an edit will take several seconds to be pushed onto the live pdf view.
3. Scrambled output. Navigating a pdf which is being generated by vimlatex results in text being scrambled/re-formatted in different fonts, especially in equation environments. 

The only way to work around the above is to `:VimtexStopAll` and `VimtexCompile` after every edit is made, which is painful. 

Running Manjaro v.21.2.6, kernel 5.15.41. My `.vimrc` vimtex config:
```
Plug 'lervag/vimtex'
    let g:tex_flavor='latex'
    let g:vimtex_view_method='mupdf'
    let g:vimtex_quickfix_mode=0
    let g:vimtex_fold_enabled=1

```
The tex packages currently installed are:
```
> pacman -Q | grep "tex"
> texinfo 6.8-2
> texlive-bibtexextra 2022.63023-1
> texlive-bin 2022.62885-1
> texlive-core 2022.63035-1
> texlive-fontsextra 2022.62977-1
> texlive-formatsextra 2022.62529-1
> texlive-games 2022.62102-1
> texlive-humanities 2022.62929-1
> texlive-latexextra 2022.63034-1
> texlive-music 2022.62533-1
> texlive-pictures 2022.62992-1
> texlive-pstricks 2022.62977-1
> texlive-publishers 2022.63013-1
> texlive-science 2022.62977-1

```

**Comment by gerw** [comment]
It seems that you are using vimtex and not vim-latex.
