### ISSUE TITLE
Tex_ViewLaTeX() doesn't open the viewer in gvim

### ISSUE THREAD

**Issue by patenteng** [vim-latex/vim-latex#221]
Tex_ViewLaTeX() doesn't open the viewer in gvim. It appears this is due to the background process execution in ftplugin/latex-suite/compiler.vim. The command on my system is `xdg-open file.pdf >/dev/null 2>&1 &`. If you use `xdg-open file.pdf >/dev/null 2>&1` instead, both vim and gvim open the viewer as a background process, as Tex_ViewLaTeX uses silent when executing the execString.

This fixes the issue for me:
```
index ecac9c1..a44eb7f 100644
--- a/ftplugin/latex-suite/compiler.vim
+++ b/ftplugin/latex-suite/compiler.vim
@@ -304,9 +304,6 @@ function! Tex_ViewLaTeX()
                        else
                                let execString .= " " . &shellredir . "/dev/null"
                        endif
-
-                       " And execute in background
-                       let execString = execString.' &'
                endif
 
        end
```

**Comment by gerw** [comment]
The command is executed in background (final `&`), since it blocks vim otherwise.

I do not see any reason why the final `&` should block / hinder the execution of the command.

Which system are you using? Can you open pdf files with

* `:!xdg-open file.pdf`
* `:!xdg-open file.pdf &`
* `:silent! !xdg-open file.pdf`
* `:silent! !xdg-open file.pdf &`
?

**Comment by patenteng** [comment]
I am on Arch with vim 9 and zsh. I did some more digging and it appears that the problem is due to the interaction of gvim with zsh.

- `:!xdg-open file.pdf` opens the file in both vim and gvim and blocks;
- `:!xdg-open file.pdf &` opens the file in vim and blocks, but file remains closed in gvim;
- `:silent! !xdg-open file.pdf` opens the file in vim and gvim without blocking;
- `:silent! !xdg-open file.pdf &` opens the file in vim without blocking, but file remains closed in gvim;
- `:!xdg-open file.pdf &; sleep 5` open the file in gvim for 5 seconds then closes; and
- `:!xdg-open file.pdf &' opens the file in gvim with `SHELL=bash`.

**Comment by patenteng** [comment]
It appears this is a bug in vim. This was solved in [issue 8314](https://github.com/vim/vim/issues/8314). Unfortunately, it was reversed in [issue 8951](https://github.com/vim/vim/issues/8951), since it prevented users from entering the user password when prompted by sudo.

They recommend using `call system("command &")` instead. So
```
diff --git a/ftplugin/latex-suite/compiler.vim b/ftplugin/latex-suite/compiler.vim
index ecac9c1..437d186 100644
--- a/ftplugin/latex-suite/compiler.vim
+++ b/ftplugin/latex-suite/compiler.vim
@@ -314,7 +314,7 @@ function! Tex_ViewLaTeX()
        let execString = substitute(execString, '\V$*', mainfname, 'g')
        call Tex_Debug("Tex_ViewLaTeX: execString = ".execString, "comp")
 
-       exec 'silent! !'.execString
+       call system(execString)
 
        if !has('gui_running')
                redraw!
```

**Comment by gerw** [comment]
Thank you for suggesting the replacement. I also escaped the file name, otherwise names with spaces cause trouble.
