### ISSUE TITLE
Stop vim-latex from opening my preamble in seperate buffer.

### ISSUE THREAD

**Issue by AbdullahZubair-UW** [vim-latex/vim-latex#222]
How can I stop vim-latex from opening my preamble files open loading the file? (It opens the preamble file in a separate buffer which for me is unnecessary).

**Comment by gerw** [comment]
I think that it can be disabled by some option. Does it help to set `let g:Tex_PackagesMenu = 0` in (e.g.) `~/.vim/ftplugins/tex.vim`?

**Comment by AbdullahZubair-UW** [comment]
Perfect that works!

**Comment by AbdullahZubair-UW** [comment]
@gerw By the way, I am an undergraduate PMATH student at the University of Waterloo in Canada. I checked out your git rep and noticed your mathbin git repo. I was wondering if this would be  useful for me in any way? (I LaTeX all my homework assignments).

**Comment by gerw** [comment]
Yes, this could be helpful, in particular for the generation of bibtex-entries from arxiv-ids or dois. I am not sure if it is particularly helpful for homework assignments.
