### ISSUE TITLE
Invalid escape sequence '\s' error

### ISSUE THREAD

**Issue by DavidCdeB** [vim-latex/vim-latex#224]
Thanks for this plugin. I'm having the following error message when opening a *.tex fie.
It looks like other users are having this same error message; see here:
https://bbs.archlinux.org/viewtopic.php?id=295424

Error:

```
"main.tex" 417L, 11176B
Error detected while processing BufRead Autocommands for "*.tex"..function dist#ft#FTtex[49]..FileType Autocommands for "*"..function <SNR>7_LoadFTPlugin[18]..script /usr/share/vim/vimfiles/ftplu
gin/tex_latexSuite.vim[12]../usr/share/vim/vimfiles/ftplugin/latex-suite/main.vim[969]../usr/share/vim/vimfiles/ftplugin/latex-suite/texviewer.vim:
line  895:
/usr/share/vim/vimfiles/ftplugin/latex-suite/bibtools.py:34: SyntaxWarning: invalid escape sequence '\s'
  """
```

**Comment by gerw** [comment]
Thank you for the report. This was fixed quite recently. Can you try if the latest version works for you?

**Comment by ArchangeGabriel** [comment]
It’s indeed fixed by https://github.com/vim-latex/vim-latex/pull/223. Do you plan to tag a new release? The last one is more than 6 years old.

**Comment by gerw** [comment]
Nice to hear.

Actually, I do not know how to release a new version. I am not a maintainer...

**Comment by ArchangeGabriel** [comment]
@gerw you should be able to follow instructions at https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository I guess.
