### ISSUE TITLE
Cannot compile bibtext files with python enabled anymore

### ISSUE THREAD

**Issue by ronisbr** [vim-latex/vim-latex#36]
Hi guys!

Sometime ago, I started to have a problem with vim-latex. It is not compiling bibtex files when I execute `\ll`. It turns out that the problem was related with the call:
```
Tex_IsPresentInFile('\v\\bibdata|\\abx', mainFileName_root.'.aux')
```
If I change this line to:
```
Tex_IsPresentInFile('\\bibdata|\\abx', mainFileName_root.'.aux')
```
then everything starts to work. Another solution is to set:
```
let g:Tex_UsePython              = 0   
```
However, I do not like this option.

Can anyone help me to figure out what is wrong with the python function here?
`/usr/bin/python` in openSUSE is Python 2.7.10. I was trying to change the version to Python 3.4 but it seems that there is not an easy way to do that in vim-latex.

Regards,
Ronan

**Comment by ixjlyons** [comment]
The problem was introduced with commit 83d49ac. It is the inverse of the exact change you mention.

@strv could you comment on why that commit was necessary?

**Comment by lrtfm** [comment]
This plugin also cannot compile bibtext files without python (`has('python')` returns `0`) in my laptop. In my computer.  
 The problem was also related with the call:
`Tex_IsPresentInFile('\\bibdata|\\abx', mainFileName_root.'.aux')`
So I change this line to:
`Tex_IsPresentInFile('\\bibdata\|\\abx', mainFileName_root.'.aux')`
Then, everything is ok!
When without python, the real call is

	function! Tex_IsPresentInFile(regexp, filename)
		call Tex_GotoTempFile()

		silent! 1,$ d _
		let _report = &report
		let _sc = &sc
		set report=9999999 nosc
		exec 'silent! 0r! '.g:Tex_CatCmd.' '.a:filename
		set nomod
		let &report = _report
		let &sc = _sc

		if search(a:regexp, 'w')
			let retval = 1
		else
			let retval = 0
		endif
		silent! bd
		return retval
	endfunction

In vim, branches are separated by `\|`. Why `|` works well?

**Comment by ronisbr** [comment]
@lrtfm, what OS are you using?
Here, if I use the line:
```
Tex_IsPresentInFile('\v\\bibdata|\\abx', mainFileName_root.'.aux')
```
Everything works fine. I'm using openSUSE Tumbleweed.

**Comment by lrtfm** [comment]
@ronisbr, I am using windows 10. 
Maybe this is the reason why I have trouble with `|`.

**Comment by ec-cwang** [comment]
I don't like the solution neither:(
```vim
let g:Tex_UsePython  = 0   
```
Cuz that will make F9 cite completion do not work any longer, which apparently depends on python:
```vim
"ftplugin/latex-suite/texviewer.vim line 107-111
			if has('python') && Tex_GetVarValue('Tex_UsePython') 
				\ && Tex_GetVarValue('Tex_UseCiteCompletionVer2') == 1

				exe 'cd '.s:origdir
				silent! call Tex_StartCiteCompletion()
```

**Comment by Norival** [comment]
Hi!
I have the same issue here and the modification you mention does not work.

The only solution I have is to disable python (`let g:Tex_UsePython = 0`) or to use vim with python3. Then compilation works fine but the `cite{}` completion does not work.

**Comment by gerw** [comment]
Please check whether it works again (also with python enabled).

**Comment by ixjlyons** [comment]
Works for me :thumbsup:

**Comment by Norival** [comment]
Works fine, thanks! =)

**Comment by gerw** [comment]
Thank you for your replies! Glad that it worked.
