### ISSUE TITLE
typing {} inserts <++> automatically.

### ISSUE THREAD

**Issue by TheGrandmother** [vim-latex/vim-latex#40]
Every time i write a `{` followed by a `}` without writing anything in between `<++>` gets inserted after the `}`

This is rather annoying...

How do i disable it or make it not break compilation after having installed the brackets plugin.

This breaks the compilation.

**Comment by tpavlic** [comment]
That is a feature. Hit Cntrl-J and your cursor will jump to the position of
the <++> and remove it. This function is intended to make navigation around
inserted structures (like auto-inserted equation environments) or your own
templates easier. Think of it like merge codes in a conventional word
processor.

I believe this is covered in depth in the vim-latex documentation.

  --Ted

Sent from the mobile device of Ted Pavlic.
Please excuse typos, swypos, or very brief responses.

**Comment by chantisnake** [comment]
you can reset this macro. using the `IMAP` function defined in vim-latex.
http://vim-latex.sourceforge.net/documentation/latex-suite/ls-new-macros.html

**Comment by gerw** [comment]
@TheGrandmother What do you mean by your last two sentences? What is the brackets plugin? Which compilation breaks?
