### ISSUE TITLE
Problem with compile when path contains '#' character

### ISSUE THREAD

**Issue by leosenko** [vim-latex/vim-latex#41]
When path to the tex file contains '#', then during compilation (\ll) gvim gives:

> Error detect ed while processing f unct ion Tex_RunlaTeX .. Tex_CD:
> line 1:
> E194 : No alternate file name to substitute for '#': cd $path_with_#
> Error detected while processing function Tex_RunLaTeX.. Tex_CompileMultipleTimes..Tex CD:
> line 1:
> E194: No alternate file name to substitute for '#': $path_with_#

The error note disappears immediately so it is difficult to notice the error.
In my case $path_with_# = D:\data\somefolder#badfolder\test.tex
ViM is in version 7.4, this has been observed on Windows 7 x64, latex is MikTex. latex $path_with_# does not give any errors.

**Comment by gerw** [comment]
This should be fixed now. Could you try it again?
