### ISSUE TITLE
is there a way to disable smart backspace?

### ISSUE THREAD

**Issue by chantisnake** [vim-latex/vim-latex#46]
I recently have an issue when I am editing latex: the backspace sometime do not deletes character, simply moves cursor.. 

I checked the <BS> key is controlled by vim-latex's smart-backspace, therefore I want to disable it to see if the error occurs again.

**Comment by gerw** [comment]
You can use `let g:Tex_SmartKeyBS = 0` in your `~/.vim/ftplugins/tex.vim`.
