### ISSUE TITLE
`IMAP()` doesn't work if lhs contains `.`

### ISSUE THREAD

**Issue by ycerd** [vim-latex/vim-latex#49]
I used the following command when editing a `.tex` file:
```VimL
:call IMAP(',.','<++>','tex','phs','phe')
```
In insert mode, I typed `,.`.

What I expected:

- The two characters would be replaced by `<++>`, cursor staying after.

What I got:

- Just `,.`

Then I tried other patterns like `,;` instead of `,.`, which worked as expected as long as no `.` appears in the first argument of `IMAP()`.

**Comment by gerw** [comment]
This is caused by the smart-dot feature (replaces three dots in a row with `\ldots`). You can disable this feature by `let g:Tex_SmartKeyDot = 0` in your `~/.vim/ftplugins/tex.vim`.

Did this resolves your issue?

**Comment by ycerd** [comment]
Thanks, this is exactly what I was looking for.
