### ISSUE TITLE
Behaviour of imap completion depends on the `backspace` setting

### ISSUE THREAD

**Issue by gerw** [vim-latex/vim-latex#53]
If the `backspace` setting does not include `start`, various imap completions do not work as expected.

To reproduce:
- `set backspace-=start`
- Type `EDO`

Expected result:

``` latex
\documentclass[<+options+>]{<+class+>}

\begin{document}
<++>
\end{document}
```

Real result:

``` latex
EDO\documentclass[<+options+>]{<+class+>}

\begin{document}
<++>
\end{document}
```

**Comment by MrQubo** [comment]
It works as expected for me.

**Comment by gerw** [comment]
I am also not (no longer?) able to reproduce it. Thank you for your feedback!
