### ISSUE TITLE
Why don't provided some stable version here?

### ISSUE THREAD

**Issue by vanabel** [vim-latex/vim-latex#56]
I found the neweast version has some problem in insert references. Ideally it should be get the _OUTLINE_ file pop up when I type `\cite{` and then press `F9`, the problem is that the _OUTLINE_ file is always empty. If I use the version on (SF](https://sourceforge.net/projects/vim-latex/), it works fine but has the known bug for change the environment as stated [here](http://stackoverflow.com/questions/7366771/vim-latex-suite-is-not-changing-the-environment-properly-how-can-i-fix-this).

In consider of all the above stated problems, may I suggest to provided some stable version of this great plugin?

**Comment by gerw** [comment]
I cannot reproduce a bug concerning `\cite`-completion. Could you file a different bug report?

Having some stable version would be a good idea in my opinion.

@tyll What do you think?

**Comment by vanabel** [comment]
I don't know how to get the log, but I get the following error:

>Name Error: name 'Tex_BibFile' is not defined

**Comment by gerw** [comment]
This might be a issue with the built-in python. Please file a different bug report.

**Comment by vanabel** [comment]
I endup the issue by uninstall python2.7.2 and install phtyon3 in cygwin64.

**Comment by tyll** [comment]
Sorry for the delay, I will prepare a new snapshot release on SF.net within the next days.

**Comment by gerw** [comment]
@tyll: In this case, we should also bump the version number to 1.9(?) -- it didn't change since May 2006. And we should also tag the corresponding commit here on github.

**Comment by gerw** [comment]
Hallo Till,

wie sieht es aus mit einer neuen Version?

Würde es sich nicht auch anbieten, die SF-Seite ganz stillzulegen?

Viele Grüße
Gerd

**Comment by tyll** [comment]
Thank you for your patience. There is now a new 1.9.0 release. For now I also uploaded it to sourceforge since the webpage and mailing list are still there.

**Comment by gerw** [comment]
There is another version number in https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/version.vim which should be updated.
