### ISSUE TITLE
Is this GitHub better than SourceForge?

### ISSUE THREAD

**Issue by mstaal** [vim-latex/vim-latex#57]
I can see that small changes to the code are made every now and then in here. But the latest release on SourceForge is from 2014. Should I rather use the code in here, or is it unstable? Plus, I would much rather use this web site than SourceForge. Could you migrate to here? With a README and a Wiki perhaps?

**Comment by tpavlic** [comment]
Michael --

You should be using the github repository. In particular:

https://github.com/vim-latex/vim-latex

There are some documents on the SF page that need to be updated, but the
official repo moved to GitHub a long time ago.

Best --
Ted



On Mon, Jul 11, 2016 at 4:17 PM, Michael Staal-Olsen <
notifications@github.com> wrote:

> I can see that small changes to the code are made every now and then in
> here. But the latest release on SourceForge is from 2014. Should I rather
> use the code in here, or is it unstable? Plus, I would much rather use this
> web site than SourceForge. Could you migrate to here? With a README and a
> Wiki perhaps?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vim-latex/vim-latex/issues/57>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAIYzxRxa01kv5BtNqUB7Z6xG32KrKn8ks5qUs8BgaJpZM4JJ5GS>
> .
>



-- 
Ted Pavlic <ted@tedpavlic.com>

**Comment by mstaal** [comment]
Thanks for the advice, Ted!
Do you know of any way to "fork" the repository into another repository? I try to make a repository with all of my dot files, configs and what not.

For the SF page: Couldn't you make a Wiki and/or README with all the documentation from over there? That would make it much simpler for people to understand how to get the latest version - and how to install the system at all.

**Comment by tpavlic** [comment]
Michael --

The traditional way to do something like you want is to use a vim script
like pathogen:

http://www.vim.org/scripts/script.php?script_id=2332

With pathogen, you create a .vim/bundle folder that contains git
repositories like vim-latex. Those repositories will be virtually "merged"
into your .vim hierarchy automatically by pathogen without actually having
to move any files. You could probably then revision control your .vim
folder with the .vim/bundle being incorporated as something like a Git
submodule:

https://git-scm.com/book/en/v2/Git-Tools-Submodules

I hope that helps.

--Ted

On Mon, Jul 11, 2016 at 6:42 PM, Michael Staal-Olsen <
notifications@github.com> wrote:

> Thanks for the advice, Ted!
> Do you know of any way to "fork" the repository into another repository? I
> try to make a repository with all of my dot files, configs and what not.
>
> For the SF page: Couldn't you make a Wiki and/or README with all the
> documentation from over there? That would make it much simpler for people
> to understand how to get the latest version - and how to install the system
> at all.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/vim-latex/vim-latex/issues/57#issuecomment-231915135>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIYz27hqXGj7jCyTH6Cq7lIKFeGkJbWks5qUvEKgaJpZM4JJ5GS>
> .
>



-- 
Ted Pavlic <ted@tedpavlic.com>
