### ISSUE TITLE
Autocomplete \cite does not work with 'autochdir'

### ISSUE THREAD

**Issue by noelfarrugia09** [vim-latex/vim-latex#58]
I have a multiple file directory and when I hit <F9> on a cite command in a file that is not the main file no suggestions are shown. I've uploaded a small working copy that showcases the issue. When I am editing chapter1.tex and insert ~\cite{ and press <F9> the suggestion box is empty. If I press <F9> in main.tex the references will show. I've uploaded my vimrc file for reference as well.

I am using the latex vim-latex from master and I am running OS X El Capitan V 10.11.6

Thank you for your time.

Regards,
Noel

[vimrc.zip](https://github.com/vim-latex/vim-latex/files/375398/vimrc.zip)
[test.zip](https://github.com/vim-latex/vim-latex/files/375396/test.zip)

**Comment by gerw** [comment]
I cannot reproduce this bug. I did not look into your vimrc settings.

* How do you open `chapter1/chapter1.tex`?
* Does the bug also appear if you place `chapter1.tex` in the same directory as `main.tex`?
* What does `` say while editing `chapter1.tex`?
* Please enable debug output and post the content of `vim-latex-suite.log` after trying to complete a `\cite`-command in `chapter1.tex`. It can be enabled via (in `.vimrc` or `ftplugin/tex.vim`):
````vim
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
````

**Comment by noelfarrugia09** [comment]
How do you open chapter1/chapter1.tex?
  vim chapter1/chapter1.tex OR open main.tex and use the "gf" command

Does the bug also appear if you place chapter1.tex in the same directory as main.tex?
  No it does not.

What does `say while editingchapter1.tex`?
  Sorry did not understand the question

The log file is attached.
[vim-latex-suite.log.zip](https://github.com/vim-latex/vim-latex/files/375455/vim-latex-suite.log.zip)

**Comment by gerw** [comment]
Oh, the third bullet got scrambled. Please try `echo Tex_GetMainFileName(':p')` while editing `chapter1/chapter1.tex`.

**Comment by noelfarrugia09** [comment]
/Users/<username>/repos/documents/test/main.tex

It is the correct location for the main file.

**Comment by gerw** [comment]
Ok. I found the problem: `set autochdir`. Can you remove that line in your `.vimrc`? Does the bug disappear?

**Comment by noelfarrugia09** [comment]
Yes it does! 👍

Do you have any solution for the `autochdir` command because it was quite useful to have vim's directory equal to that of the file.

Thanks a lot for your time.

**Comment by gerw** [comment]
I would classify that as a bug inside latex-suite. I will try to fix it, but it might take some time.

**Comment by noelfarrugia09** [comment]
That's great. Thank you for your prompt support :)

**Comment by gerw** [comment]
Finally, I tracked this bug down. Can you confirm that it does work now?

**Comment by noelfarrugia09** [comment]
Hi Gerd,

I converted to using emacs over the past months so I no longer have VIM set up :(. I apologise for any inconvenience cause. 

Kind Regards,

Noel

On Fri, 03 Feb 2017 at 22:29 Gerd Wachsmuth

<
mailto:Gerd Wachsmuth <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Finally, I tracked this bug down. Can you confirm that it does work now?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/vim-latex/vim-latex/issues/58#issuecomment-277367152
, or
