### ISSUE TITLE
The lastest commit `c7aa5fa` breaks EDO

### ISSUE THREAD

**Issue by duguyipiao** [vim-latex/vim-latex#59]
To reproduce:

1. Open a new tex file
2. Type EDO

Expected result:

```tex
\documentclass[<+options+>]{<+class+>}

\begin{document}
<++>
\end{document}
```

Real result:

```tex
E\documentclass[<+options+>]{<+class+>}

\begin{document}
<++>
\end{document}
```

EDO works correctly before the latest commit `c7aa5fa`.

Test with vim 7.4 and python 2.7.12

**Comment by gerw** [comment]
Thank you for reporting. I found the problem: `<c-v>O` does not behave as expected. In fact, `<c-v>O112` produces `J`. This 'feature' seems not to be described in the documentation of vim. I am not sure what to do here.

**Comment by gerw** [comment]
Oh, I see, octal `112` is decimal `74`, which is the ASCII code for `J`.
