### ISSUE TITLE
'\cite{+<F9>" not work with newest python 2.7.*

### ISSUE THREAD

**Issue by vanabel** [vim-latex/vim-latex#60]
If I type "\cite{" then press F9, after type `a` I will get the following error:

> Name Error: name 'Tex_BibFile' is not defined

which maybe a bug and can be fixed by upgrade to python3. I install python3 in windows7 by cygwin64.

![install_python3](https://cloud.githubusercontent.com/assets/4273353/17331879/67f3a4a6-58ff-11e6-97e1-c15bdb367bef.PNG)

**Comment by gerw** [comment]
As already said, I cannot reproduce the bug. Hence, I have no idea what is going wrong and how to fix it.

**Comment by lucc** [comment]
@vanabel What is `<F9>` calling? Try to find out with `:verbose map <F9>` and then try to reproduce the error by calling the relevant functions directly.
