### ISSUE TITLE
`section`+`F5` Bug?

### ISSUE THREAD

**Issue by duguyipiao** [vim-latex/vim-latex#61]
To reproduce:

```
1. Open a new tex file
2. Type `section`
3. Press `F5`
```

Expected result:

``` tex
\section{<++>}<++>
```

Real result:

``` tex
0\section{<++>}<++>
```

Test with vim 7.4 and python 2.7.12

**Comment by gerw** [comment]
With `F7` instead of `F5` you get your expected result. (You can also use `SSE` to save some keystrokes)

`F5` is for environment completion and `\section{...}` is not an environment. However, I do not know why `F5` produces this output.

**Comment by gerw** [comment]
I found the source for this behaviour:

https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/envmacros.vim#L583

Here, the existence of the function `Tex_section` is checked and the result is inserted at the cursor position. However, this function exists for a different reason and already inserts the text and returns `0` (which is also inserted).

I do not see any reason for the above mentioned check and this 'feature' is also not documented. It has also different side-effects: You can call any function of name `Tex_something` by `something<F5>`, which seems to be pretty weird.

If there are no objections, I would like to remove that check in line 583.

**Comment by duguyipiao** [comment]
Thank for the explanation. I misunderstand this because when I use `F5` in preamble, it complete `usepackage`. For example, when I type `xcolor` and press `F5`, `\usepackage{xcolor}` is returned. I wonder whether removing that check in line 583 will damage similar completions of `F5`.

**Comment by lucc** [comment]
You can find out what `<F5>` is bound to if you execute `:verbose map <F5>`. What is the output?
