### ISSUE TITLE
Indentation goes crazy by template inserting 

### ISSUE THREAD

**Issue by zuxfoucault** [vim-latex/vim-latex#63]
I'm not sure if anyone have similar problems, but when I `:TTemplat` my custom template. The indentation will keep incremented. 

The work around for me was to modified the templates.vim file as following:
Start with line:137
``` 
	com! -complete=custom,Tex_CompleteTemplateName -nargs=? TTemplate :se paste
		\| :call <SID>ReadTemplate(<f-args>)
		\| :se nopaste
```
Any better suggestions?

**Comment by gerw** [comment]
Your template file should not contain any indentation. After insertion of the template, the indentation is set up by the indentation script `indent/tex.vim`.

**Comment by gerw** [comment]
Anyway, if one would like to use indented templates, one should set `nopaste` around line 47 in `templates.vim`.

**Comment by zuxfoucault** [comment]
Thanks!
1. Did you mean set `nopaste` inside function `ReadTemplate`?

2. Even I didn't contain any indentation in my template, lines after `\newcommand{}{}` in the preamble will still automatic indent for the rest of the file.

**Comment by gerw** [comment]
1. Yes.
2. May I have a look at your template?

**Comment by zuxfoucault** [comment]
Sure! And sorry for late reply!
[https://gist.github.com/zuxfoucault/2461e3561013334f3a663f6c20003222](https://gist.github.com/zuxfoucault/2461e3561013334f3a663f6c20003222)

**Comment by gerw** [comment]
In my opinion, there are two problems in your template:

* There is some indentation in lines 45-48 and 102.
* A closing `}` is missing for the command in line 55.

If I fix these problems, the indentation is as expected.

Does this fix your indentation problems?

**Comment by zuxfoucault** [comment]
Yes, the indentation problem fixed. Thanks a lot!!!
