### ISSUE TITLE
type e^^ but I get wrong result

### ISSUE THREAD

**Issue by AmyAckerRoot** [vim-latex/vim-latex#66]
To reproduce:
```
1. open a .tex file
2. enter "equation" and then press "F5"
3. type e^^
```
Expected result:
```tex
e^{}<++>
```
Real result:
```tex
e<++>
```
Test with vim 8.0 on Xubuntu

**Comment by gerw** [comment]
Can you explain how you fixed your problem? Maybe this will help others facing the same issue.
