### ISSUE TITLE
Problem with "set noimd" when using Korean

### ISSUE THREAD

**Issue by liganega** [vim-latex/vim-latex#67]
I am using the newest MacVim on Sierra and sometimes write latex in Korean.
The vim-latex plugin is installed by using "vimplug".

The problem with Korean is that the vim hotkeys does not work in Korean, so I used to use the trick using "set noimd" which automatically change the input language when exiting the insert mode.

It works fine with other plugins, but with vim-latex I get problems when writing Korean.
For example, when I write "Welcome" in Korean, it should look like as follows:

"환영합니다"

But with vim-latex mode, it looks like as follows:

"ㅎㅗㅏㄴㅇㅕㅇㅎㅏㅂㄴㅣㄷㅏ"

That is, syllables are shown as alphabets are taken apart.
And when "set noimd" is commented out, then everything ok. 

Any idea how to solve this problem? 
Buy the way, I tested the "vimtex" plugin, but the problem did not occur.

**Comment by gerw** [comment]
Do you know how I could try to reproduce the bug with a western keyboard?

**Comment by liganega** [comment]
You just need to install and select Korean on your system, and type 

ghksdudgkqslek. 

Then it should originally look like

환영합니다

which means "Welcome" in English. But with vim-latex mode, it looks like 

호ㅏㄴ여ㅇㅎㅏㅂ니다

In Mac, you can install and select "2-Set Korean". 
In Ubuntu e.g., you need "nabi, ibus, ibus-hangul", and select "한국어" (Korean, in English).

**Comment by gerw** [comment]
Can you try to set `let g:Tex_SmartKeyBS = 0` (in your `.vim/ftplugin/tex.vim`)? For me, this resolved your issue.

**Comment by liganega** [comment]
It's perfect! Thank you so much.
