### ISSUE TITLE
Unpredictable jumps after compilation

### ISSUE THREAD

**Issue by s-bl** [vim-latex/vim-latex#68]
Hey,

since recently vim jumps - at least for me in a unpredictable way - around either in the current buffer or it jumps into another recently opened (but now closed) file (can also be the window of NERDTree, so i guess it does not try to jump to an error) after compilation, which is kind of cumbersome.
I try to compile a multi file project with multiple .tex files in different sub-directories.
I run archlinux with vim 8.0 and the latest git version of vim-latex from the aur [aur:vim-latexsuite-git](https://aur.archlinux.org/packages/vim-latexsuite-git/).

The relevant options in my vimrc are

```
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats = 'pdf'
let g:Tex_CompileRule_pdf = '/usr/local/texlive/2016/bin/x86_64-linux/pdflatex -  interaction=nonstopmode -shell-escape $*'
let g:Tex_ViewRule_pdf = 'zathura -l error'
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"

" Don't go to error
let g:Tex_GotoError = 0

let g:Tex_IgnoredWarnings =
\'Underfull'."\n".
\'Overfull'."\n".
\'specifier changed to'."\n".
\'You have requested'."\n".
\'Missing number, treated as zero.'."\n".
\'There were undefined references'."\n".
\'Citation %.%# undefined'."\n".
\'multiply defined.'."\n".
\'There were multiply-defined labels.'."\n".
\'undefined on input'."\n".
\'contains only floats'."\n".
\'Float too large'."\n".
\'Reference'."\n".
\'LaTeX Font Warning'."\n"
let g:Tex_IgnoreLevel = 14`
```

As already mentioned, this behavior is fairly new but i can't really determine at which point it started. I haven't tried to downgrade vim, though. Maybe it is related to the recent update to vim 8.0?

Any suggestions?

Anyways, thanks for your work on vim-latex, i really appreciate it.

best,

s-bl

**Comment by gerw** [comment]
I cannot reproduce this behavior. Can you set up a complete, minimal working example to reproduce the bug?

**Comment by s-bl** [comment]
I will try to come up with something, thx.
