### ISSUE TITLE
Question: How to creating new syntax items or group under vim-latex context?

### ISSUE THREAD

**Issue by zuxfoucault** [vim-latex/vim-latex#69]
I tried to define my own syntax item for my custom match patterns, as following:
```
hi def syn1 guifg=#ff5f00
syntax match syn1 /%||[A-Za-z0-9]\+\>.*/
```
But the snippet didn't work within \begin{document} \end{document} environment.

If I change syn1 to vim-latex or vim biuld-in syntex item, say `texStatment`, such as
```syntax match texStatment /%||[A-Za-z0-9]\+\>.*/```
, it works well!

Any suggestions about how to create new syntax item that works within \begin{document} \end{document} environment?

Thanks!

**Comment by gerw** [comment]
The latex-suite does not provide any syntax highlighting for tex-files.
