### ISSUE TITLE
Normal mode key maping using langmap caries over to insert mode

### ISSUE THREAD

**Issue by Anstow** [vim-latex/vim-latex#7]
When using langmap to remap keys in normal mode, when using latex plugin (installed using vundle) the mapping still occurs in insert mode.

From memory this doesn't happen on my home machine where I have root access and have installed using my package manager (pacman).

**Comment by gerw** [comment]
I cannot reproduce this behaviour. I opened vim on a texfile and used `:set langmap=ad`. Then, I get `a` in insertmode and `d` in normal mode.

**Comment by Anstow** [comment]
I think I was referring to the shortcuts like `d for \delta being remapped when langmap is used. But this is (probably) expected behaviour. I guess with hindsight this (probably) isn't a bug.

**Comment by Anstow** [comment]
Actually, this behaviour seems to have been fixed sometime between vim 7.4.2143 and 7.4.2334. But I can't find any documentation of the fix.

**Comment by Anstow** [comment]
Looking at the patches in more detail. I believe it is patch 7.4.2236 and using the `nolangremap` option.

**Comment by gerw** [comment]
Thank you for your follow-up!
