### ISSUE TITLE
Can't type char 'é' in TeX files

### ISSUE THREAD

**Issue by m2vihand** [vim-latex/vim-latex#70]
Hi there!

Thank you for developing vim-latex! Looks great. However I have an issue editing .tex files with vim.

I'm not English, so i need these special characters: á,é,í,ó,ö,ő,ú,ü,ű. All of them seems to work except 'é'. I can type it as a digraph (e'), but it's not really fast this way. It seems i can type 'é' in non .tex files.

I've installed vim-latex via Vundle.

Could anybody help me type é from keyboard? Any ideas? Thanks in advance. :)

**Comment by m2vihand** [comment]
Just one more thing: I'm using Windows 10.

**Comment by gerw** [comment]
See http://vim-latex.sourceforge.net/index.php?subject=faq&title=FAQ#faq-e-acute or https://github.com/vim-latex/vim-latex/issues/14

**Comment by gerw** [comment]
I changed a default setting. Now, it should work out-of-the-box with the latest upstream version.

**Comment by m2vihand** [comment]
I'm sorry, I'm new to Vim, especially to vim-latex. I've managed to fix this. Thank you really much. :) I've changed that thing in #14, i've sourced again and it works fine. :)

**Comment by gerw** [comment]
You are welcome. No problem, this is/was a regular issue with the latex-suite and many people stumbled upon é :)
