### ISSUE TITLE
No way to disable annoying IMAPs

### ISSUE THREAD

**Issue by jwakely** [vim-latex/vim-latex#72]
The following mapping are extremely annoying when trying to edit the [LaTeX sources of the C++ standard](https://github.com/cplusplus/draft/) because most of them are very common sequences in C++ code:

	call IMAP ('__', '_{<++>}<++>', "tex")
	call IMAP ('()', '(<++>)<++>', "tex")
	call IMAP ('[]', '[<++>]<++>', "tex")
	call IMAP ('{}', '{<++>}<++>', "tex")
	call IMAP ('^^', '^{<++>}<++>', "tex")
	call IMAP ('$$', '$<++>$<++>', "tex")
	call IMAP ('==', '&=& ', "tex")
	call IMAP ('~~', '&\approx& ', "tex")
	call IMAP ('=~', '\approx', "tex")
	call IMAP ('::', '\dots', "tex")
	call IMAP ('((', '\left( <++> \right)<++>', "tex")
	call IMAP ('[[', '\left[ <++> \right]<++>', "tex")
	call IMAP ('{{', '\left\{ <++> \right\}<++>', "tex")

For example, it's not possible to write `std::string` in the C++ source because it gets changed to `std\dotsstring` (which isn't even valid LaTeX!)

These mappings should be optional, instead of assuming that every user of the latex-suite files wants them.

The mappings that start with Tex_Leader are OK, as they don't happen while entering plain text, so they don't hijack normal keys.

**Comment by gerw** [comment]
I think there are more LaTeX users that do not edit the sources of the C++ standard than those who edit these sources. Hence, it is reasonable to assume that every user wants those mappings.

However, there could be an option to disable them. Until this is the case, you could disable the mappings by doing
`call IMAP('__','__')` in your `.vim/after/tex.vim`.
It would also be nice to have an `IUNMAP`-function.

**Comment by jwakely** [comment]
> Hence, it is reasonable to assume that every user wants those mappings.

It's perfectly reasonable to assume _most_ users want them, it's not reasonable to assume every user wants them, and that's why they should be optional.

**Comment by jwakely** [comment]
`call IMAP('__','__', "tex")` works, thanks.

**Comment by gerw** [comment]
Using this argument, **all features of latex-suite should be optional**, since for every feature there is at least one user which do not want to use this particular feature. This is, of course, nonsense.

**Comment by jwakely** [comment]
No, because not all features interfere with the normal behaviour of vim. Entering text in input mode is a fairly basic function, and hijacking it with no easy way to disable it is impolite.

As I said above:

> The mappings that start with Tex_Leader are OK, as they don't happen while entering plain text, so they don't hijack normal keys.

Even if Tex_Leader conflicts with my default Leader, I can change that to keep the feature without clashing with other features. That isn't the case for the mappings I'm objecting to. Please don't put stupid words in my mouth that I didn't say.

**Comment by jwakely** [comment]
And the C++ standard sources are just an example. Obviously the same problem exists for other people who try to enter `{}` etc. and want it entered verbatim.

**Comment by gerw** [comment]
Now I have added a `IUNMAP` function to remove `IMAP`s.
