### ISSUE TITLE
helptags error

### ISSUE THREAD

**Issue by bdcaf** [vim-latex/vim-latex#77]
When installing with [dein](https://github.com/Shougo/dein.vim) I get errors like:
```
[dein] Error generating helptags:
[dein] Vim(helptags):E154: Duplicate tag "align" ...
```
(freely translated)

First I consider removing the offending "Align" plugin - but then the next popped up "tabular".
I managed to drill it down to the doc/latexhelp.txt file which creates many tags. 
Since this file interferes with several plugins and I feel greater need to have help for actual vim plugins personally I decided to remove it.

**Comment by gerw** [comment]
Indeed, there was a collision of helptags with the align plugin. Maybe there are even more.

Since this `latexhelp.txt` is mostly outdated (last change 2001), I would also remove it from the repository. Does anybody have objections?

**Comment by alick** [comment]
Came across this when I am trying to report a bug for that doc (`*{num}{cols}`)... I find that help file handy, but the points made here are fair enough. So farewell...

**Comment by gerw** [comment]
You can still put this file in `~/.vim/doc/`.
