### ISSUE TITLE
Getting two starting double quotes

### ISSUE THREAD

**Issue by Neur1n** [vim-latex/vim-latex#78]
Normally when I type the quote (") twice, I would get

```
``''<++> 
```
But recently when I start to insert texts, this environment becomes 

```
````<texts>''<++> 
```

Another starting double quote would be inserted automatically along with a "beep" sound. It happens both in unix and dos formats file running in Windows 7, but it didn't happen before.
The folowing is the configurations for vim-latex in my vimrc:

```vim
set shellslash
set grepprg=grep\ -nH\ $*
let Tex_FoldedSections=""
let Tex_FoldedEnvironments=""
let Tex_FoldedMisc=""
let g:tex_flavor='latex'
let g:Tex_CompileRule_pdf = 'pdflatex -interaction=nonstopmode $*'
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats='pdf,aux'
let g:Tex_ViewRule_pdf = 'E:\ProgramFiles\SumatraPDF\SumatraPDF.exe'

function CompileXeTex()  "|use xelatex to compile temporarily
    let oldCompileRule=g:Tex_CompileRule_pdf
    let g:Tex_CompileRule_pdf = 'xelatex -interaction=nonstopmode $*'
    call Tex_RunLaTeX()
    let g:Tex_CompileRule_pdf=oldCompileRule
endfunction
map <Leader>lx :<C-U>call CompileXeTex()<CR>
```

Any help is much appreciated.

**Comment by gerw** [comment]
I cannot reproduce this behavior. It may depend on you vim configuration. Do you know which commit induces this bug?

**Comment by Neur1n** [comment]
This is what I got

```
$ git log
commit 0e832ae9f3841fed1e72fe8cc1180ef02c70d578
Author: Gerd Wachsmuth <gerd.wachsmuth@mathematik.tu-chemnitz.de>
Date:   Wed Dec 28 21:57:54 2016 +0100

    Add IUNMAP function.
```

It may depend on my vim configuration as you say. I have been changing it a lot recently.
It is fine that when I type the quote once then insert texts then type another quote.
Thanks for the response.

**Comment by gerw** [comment]
I tried your `vimrc` (but without all the plugins) and, still, cannot reproduce the bug.

Could you try to create a debug log
````
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
````
while typing? What does appear in the log after the first `"` and after the second `"`?

**Comment by Neur1n** [comment]
The following is the debug output when I type the first `"` and compile
```
comp : +Tex_RunLaTeX, b:fragmentFile = 0
comp : Tex_RunLaTeX: compiling to target [pdf]
comp : Tex_RunLaTeX: getting dependency chain = [pdf]
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : Tex_RunLaTeX: setting target to pdf
comp : Tex_RunLaTeX: compiling file multiple times via Tex_CompileMultipleTimes
comp : Tex_CompileMultipleTimes: latex run number : 1
comp : Tex_CompileLatex: getting mainfname = [test.tex] from Tex_GetMainFileName
comp : Tex_CompileLatex: execing [make! test.tex]
comp : Tex_CompileMultipleTimes: errors = [
 1: (test.aux) [1{C:/ProgramDat]
comp : Tex_CompileMultipleTimes: Ran latex 1 time(s)
comp : Tex_RunLaTeX: errlist = [
 1: (test.aux)
 2:  ]
comp : Tex_SetupErrorWindow: mfnlog = test.log
comp : -Tex_RunLaTeX
```
Then the second `"` and compile
```
comp : +Tex_RunLaTeX, b:fragmentFile = 0
comp : Tex_RunLaTeX: compiling to target [pdf]
comp : Tex_RunLaTeX: getting dependency chain = [pdf]
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : Tex_RunLaTeX: setting target to pdf
comp : Tex_RunLaTeX: compiling file multiple times via Tex_CompileMultipleTimes
comp : Tex_CompileMultipleTimes: latex run number : 1
comp : Tex_CompileLatex: getting mainfname = [test.tex] from Tex_GetMainFileName
comp : Tex_CompileLatex: execing [make! test.tex]
comp : Tex_CompileMultipleTimes: errors = [
 1: (test.aux) [1{C:/ProgramDat]
comp : Tex_CompileMultipleTimes: Ran latex 1 time(s)
comp : Tex_RunLaTeX: errlist = [
 1: (test.aux)
 2:  ]
comp : Tex_SetupErrorWindow: mfnlog = test.log
comp : -Tex_RunLaTeX
```
Then I type `test` and compile (this result in ` ````test''<++> ` in Vim)
```
comp : +Tex_RunLaTeX, b:fragmentFile = 0
comp : Tex_RunLaTeX: compiling to target [pdf]
comp : Tex_RunLaTeX: getting dependency chain = [pdf]
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : Tex_RunLaTeX: setting target to pdf
comp : Tex_RunLaTeX: compiling file multiple times via Tex_CompileMultipleTimes
comp : Tex_CompileMultipleTimes: latex run number : 1
comp : Tex_CompileLatex: getting mainfname = [test.tex] from Tex_GetMainFileName
comp : Tex_CompileLatex: execing [make! test.tex]
comp : Tex_CompileMultipleTimes: errors = [
 1: (test.aux) [1{C:/ProgramDat]
comp : Tex_CompileMultipleTimes: Ran latex 1 time(s)
comp : Tex_RunLaTeX: errlist = [
 1: (test.aux)
 2:  ]
comp : Tex_SetupErrorWindow: mfnlog = test.log
comp : -Tex_RunLaTeX
```

**Comment by Neur1n** [comment]
I was using version 8.0.0142(x86) when I got this problem. Then I just tried it with 8.0.0142(x64), 8.0.0222(x86) and 8.0.069(x86) on my 64-bit laptop, but this problem still exists.

**Comment by Neur1n** [comment]
I got something new. The following content is in my `test.tex` file:
```
\documentclass{article}
\begin{document}
test
````test''<++>
\end{document}
```
And the `test.pdf` shows:
```
test ““test”¡++¿
```
Looks like some kind of encoding problem.
I have the following in my `vimrc`
```
if has("multi_byte")
    if &termencoding == ""
        let &termencoding = &encoding
    endif
    set encoding=utf-8
    setglobal fileencoding=utf-8
    set fileencodings=utf-8,gbk,gb2312,gb18030
endif
```
But even I delete them, the PDF output didn't make any different.

Thanks for reading.

**Comment by gerw** [comment]
Are you using the recent version of latex-suiet? In your debug file, there should be a line like
```
imap : IMAP_PutTextWithMovement: text = [X^\^N:call IMAP_Mark('set')"_s<<++>>''<<++>>^\^N:call IMAP_Mark('go')i^R=IMAP_Jumpfunc('', 1)]
````

**Comment by gerw** [comment]
Your encoding is fine. For some reason, LaTeX transforms `<` and `>` into `¡` and `¿`.

**Comment by Neur1n** [comment]
I just updated the latex-suite, but I cannot get something similar. Let me list out how I operate by following your suggestion.

1. Create a new file `test.tex`;
2. Type in
```vim
:let g:Tex_Debug = 1
:let g:Tex_DebugLog = "vim-latex-suite.log"
```
3. Type in
```tex
\documentclass{article}
\begin{document}
test
``
\end{document}
```
But the debug file `vim-latex-suite.log` won't update until I compile (`\ll`) the file.
4. Didn't see anything starts with `imap`.

Is the debug file supposed to be updated simultaneously? If so, the compile rule in my `vimrc` is
```vim
let g:Tex_CompileRule_pdf = 'pdflatex -interaction=nonstopmode $*'
```
do I need to add something like `-synctex=1`, `-src-special`...?
Thanks.

**Comment by Neur1n** [comment]
Well, after I updated to the latest version, there would be a weird compilation error which didn't happen in commit `0e832ae`. I think there must be something wrong within my setup. So maybe I should close this issue.

**Comment by gerw** [comment]
Yes, the debug-file should be updated instantaneously. Typing two `"` in a row should result into something with `imap` in the log-file.

**Comment by Neur1n** [comment]
Finally I found something related. When I include either one of the following two
```vim
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
```
into my `vimrc`, this problem solved. But I couldn't anything similar in these two files or even `default.vim` (which is sourced by `vimrc_example.vim`).

**Comment by gerw** [comment]
I still cannot reproduce your behavior. In your first post, you have written that "...recently... this becomes". Do you have changed anything in your setup (new version of vim or latex-suite; changes in vimrc,...)?

**Comment by gerw** [comment]
Do you have a repository with your vim setup?

**Comment by Neur1n** [comment]
`https://github.com/Neur1n/vimfiles` - my vim setup repo. Also there is a copy of my `vimrc`  in it.

**Comment by Neur1n** [comment]
> I still cannot reproduce your behavior. In your first post, you have written that "...recently... this becomes". Do you have changed anything in your setup (new version of vim or latex-suite; changes in vimrc,...)?
It could be the change of excluding `source $VIMRUNTIME/vimrc_example.vim` and `source $VIMRUNTIME/mswin.vim` in my `vimrc`, since I excluded them when I reworked with my `vimrc`.

**Comment by gerw** [comment]
I just cloned your configuration. Still, I get the expected output. If `source $VIMRUNTIME/vimrc_example.vim` helps, you could try to investigate which line in this file cures the behavior. For example, you could append the whole file to your `.vimrc` and then delete line by line to see which line helps.

**Comment by Neur1n** [comment]
Thanks for the tip. And quickly I found I actually missed something existing in both files I mentioned, that is  the line
```vim
set backspace=indent,eol,start
````
This is not in my personal `vimrc` since I don't like such behavior.

**Comment by gerw** [comment]
Thank you! Actually, this is known to be a bug, see https://github.com/vim-latex/vim-latex/issues/53.

`backspace` has to contain at least `start`.

**Comment by Neur1n** [comment]
> Thank you! Actually, this is known to be a bug, see #53.
backspace has to contain at least start.

Yes, I just find out my problem can be solved with containing only `start` into it. And this won't backsapce to the previous line. Thank you for your help!
