### ISSUE TITLE
Smart Key Mappings are not working at all

### ISSUE THREAD

**Issue by songcai** [vim-latex/vim-latex#79]
When I type in double quotes, the default behavior is that " should be translated to `` or '' automatically depending on whether is the opening or closing quote. However, the current version (as of Feb. 17, 2017) is not doing that at all. Also, ... is not translated to \ldots automatically.

Both g:Tex_SmartKeyQuote and g:Tex_SmartKeyDot are set to 1.

I also tried "set backspace=start", not helping at all.

**Comment by gerw** [comment]
Thank you, should be fixed now.

**Comment by songcai** [comment]
Many thanks for the quick reply. I confirm that the fix works.
