### ISSUE TITLE
Vundle installation error

### ISSUE THREAD

**Issue by danieleavitabile** [vim-latex/vim-latex#80]
When I run PluginInstall on Vundle using MacVim 8.0.329 (127) on MacOSX 10.12.3 (16D32), I get the following error

Error detected while processing /Users/pmzda/.vim/bundle/LaTeX-Suite-aka-Vim-LaTeX/plugin/remoteOpen.vim:
line   33:
E174: Command already exists: add ! to replace it  

Do you know why this could happen? I attach my vimrc file if this helps.

[vimrc.txt](https://github.com/vim-latex/vim-latex/files/806857/vimrc.txt)

**Comment by gerw** [comment]
Which source does Vundle use to install 
````
Plugin 'LaTeX-Suite-aka-Vim-LaTeX'
````
?

What is on line 33 in `/Users/pmzda/.vim/bundle/LaTeX-Suite-aka-Vim-LaTeX/plugin/remoteOpen.vim`?

Maybe you should tell Vundle to install vim-latex from this github repository.

**Comment by gerw** [comment]
By the way, this has bug been fixed in https://github.com/vim-latex/vim-latex/commit/77c5977468be5d913e96116ce436b0dc2fd54756.

**Comment by danieleavitabile** [comment]
Thank you @gerw. I had to change my .vimrc from 

Plugin 'LaTeX-Suite-aka-Vim-LaTeX'

to 

Plugin 'vim-latex/vim-latex'

and it works perfectly now.
