### ISSUE TITLE
Auto-detecting bibtex flavor?

### ISSUE THREAD

**Issue by WPettersson** [vim-latex/vim-latex#81]
So I've started using Biber rather than Bibtex recently, but I haven't (and probably won't) be moving all my old papers to Biber. This means that, for now, I sometimes have to set g:Tex_BibtexFlavor = "biber"/"bibtex" depending on which project I am currently working on. Note that as long as I set BibtextFlavor correctly, biber does work just fine.

I use biber via `\usepackage[backend=biber]{biblatex}`which seems fairly easy to detect. I think a regex for `\\usepackage\[backend=\([a-z]\+\)\]{biblatex}`could spot biber here, and if so set the correct value for BibtexFlavor. I've tried to write my own code to detect this, but I'm not a vim expert and am still somewhat fumbling around in the dark.

Is there any particular reason that we don't detect this, or other ways of specifying a backend?

**Comment by gerw** [comment]
This is not done because the loading of biber could be much more complicated. I have a self-written class, which loads biber if a global option is set. Detection of this would be magic.

You can use your described approach in your `ftplugins/tex.vim`.
