### ISSUE TITLE
Potential Issue with Folding

### ISSUE THREAD

**Issue by johnbs1234** [vim-latex/vim-latex#82]
Hi there! 

I'm new to vim and latex-suite, and I'm still learning; however, I am not entirely incompetent (I hope). The issue I'm having that's bugging me is that folding in my LaTeX documents is not working properly.  When I open documents I see no folding, and when I use the \rf command and the :zR command nothing seems to work. This does not seem to be an issue with the included folding function, because when I actually opened  up the .vim files, they were properly folded! If you could provide any insight on how to get this feature up and running, I would sincerely appreciate it (before you ask, yes, it is visible when I run :scriptnames, and the \ll and \lv commands work great!)

Thank you so much for your time,

John

**Comment by gerw** [comment]
This is hard to guess. Can you show your `.vimrc` and maybe your `.vim/ftplugins/tex.vim`? What does `:setlocal indentexpr?` say when you are in a tex-file?

**Comment by johnbs1234** [comment]
Hey there, 
indentexpr = GetTexIndent()

[vimrc.txt](https://github.com/vim-latex/vim-latex/files/825688/vimrc.txt)

[tex.vim.txt](https://github.com/vim-latex/vim-latex/files/825690/tex.vim.txt)


(I hope this works the way I did it, but here is everything I believe!)
Thank you so much for your help!

John

**Comment by gerw** [comment]
Using your configuration files, folding works quite well for me. You could try to enable debugging by adding
```
let g:SyntaxFolds_Debug = 1
let g:Tex_Debug = 1
let g:Imap_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
```
to your `ftplugin/tex.vim`. Can you show `vim-latex-suite.log` after opening a tex file?

**Comment by johnbs1234** [comment]
Okay, quick note, I installed these files via the Arch Linux installation from the vim-plugins group.  After adding these lines of code you recommended to the following path (different computer with a fresh install of everything including vim but the same problem) "/usr/share/vim/vimfiles/ftplugin/tex_latexSuite.vim". After adding these lines of code, I observed no output file.  Thoughts?

**Comment by gerw** [comment]
The arch repository might contain a very old version of the latex-suite. You should try to install a newer one, e.g. the most recent version from this git repository. You might want to use a plugin manager for this, e.g., pathogen, vim-plug or Vundle.
