### ISSUE TITLE
\cite completion: empty split window

### ISSUE THREAD

**Issue by Druidefix** [vim-latex/vim-latex#84]
Hello,

this is a follow-up to #83 in - once again - a special case.

Once again I'm using the IEEE `bare_conf.tex` template and now try to add a literature entry. With the current version the split window is empty. I pinpointed commit 5f2f5e8 to cause the problem. In this case I altered the template to not use the inline definition of the bibtex entry, but to use my bib file. See the following lines for the necessary changes to reproduce.

```
% can use a bibliography generated by BibTeX as a .bbl file
% BibTeX documentation can be easily obtained at:
% http://mirror.ctan.org/biblio/bibtex/contrib/doc/
% The IEEEtran BibTeX style support page is at:
% http://www.michaelshell.org/tex/ieeetran/bibtex/
\bibliographystyle{IEEEtran}
% argument is your BibTeX string definitions and bibliography database(s)
\bibliography{IEEEabrv,druidefix.bib}
%
% <OR> manually copy in the resultant .bbl file
% set second argument of \begin to the number of references
% (used to reserve space for the reference number labels box)
% \begin{thebibliography}{1}

% \bibitem{IEEEhowto:kopka}
% H.~Kopka and P.~W. Daly, \emph{A Guide to \LaTeX}, 3rd~ed.\hskip 1em plus
%   0.5em minus 0.4em\relax Harlow, England: Addison-Wesley, 1999.

% \end{thebibliography}
```

I seems like the change to `return fnamemodify(retval, ':p')` runs into a problem, when the command `\bibliography{` has two filenames. If I either remove the `IEEEabrv,` or revert this commit everything works as expected.

**Comment by gerw** [comment]
Does my fix work for you?

**Comment by Druidefix** [comment]
As the issue was already closed, I didn't answered. But yes, your fix works perfectly for me. Thank you once again.

**Comment by monkey-jesus** [comment]
gerw you are now my favourite person in the world. This has been bugging me for such a long time. I can't thank you enough.
