### ISSUE TITLE
Cite completion does not work - empty outline view

### ISSUE THREAD

**Issue by mstaal** [vim-latex/vim-latex#87]
My outline is empty whenever I press F9. It pops up, but nothing is displayed inside of it.

**Comment by mstaal** [comment]
Could you please express entirely how .bib-files should be used with vim-LaTeX? For some reason I cannot make it work anymore. :-(

**Comment by gerw** [comment]
It is very hard to make any guess without any information. You could try to enable debugging via
````
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
````

Cite completion should work out of the box (vim should be compiled with python (either 2 or 3) and by using default settings of latex-suite).

**Comment by mjezzini** [comment]
My F9 is not working neither.  My gvim has python (i.e. :echo has('python') = 1).  Here is my log

> view : Tex_Grep('<'cite'>', '*.tex')
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [U:/GitHub/IEEEXtalk/main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
SyntaxFolds : Finished folding in   0.001073 seconds.
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [U:/GitHub/IEEEXtalk/main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
view : +Tex_SetupCWindow
view : +Tex_SyncPreviewWindow
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : :Tex_FindBibFiles: 
view : :Tex_FindBibFiles: returning []
view : :Tex_SwitchToInsertMode: 
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = Je
view : :Tex_FindBibFiles: 
view : :Tex_FindBibFiles: returning []
view : :Tex_SwitchToInsertMode:

**Comment by gerw** [comment]
Your log file indicates that latex-suite fails to find any bib-files. Can you show me your tex-file?

**Comment by mjezzini** [comment]
main.tex
``` tex
\documentclass[journal, a4paper]{IEEEtran}
\input{preamble}
\begin{document}
	\input{title_abstract}
	\input{sec/intro}
	\input{sec/validation}
	\input{sec/impedance}
	\input{sec/crosstalk}
	\input{sec/bend}
	\input{sec/conclusion}
	\input{sec/endings}
\end{document}
````
endings.tex
````tex
\appendices

\section*{Acknowledgment}
The authors would like to thank...

\bibliographystyle{IEEEtran}
\bibliography{library}

\begin{IEEEbiography}{Moises A. Jezzini}
         Biography text here.
\end{IEEEbiography}
````

**Comment by gerw** [comment]
The python based cite-completion does not work if the `\bibliography`-command is not in the main file. As a workaround, you could add `\bibliography{library}` after the `\end{document}` in `main.tex`, or you use `let g:Tex_UseCiteCompletionVer2=0` a non-python based cite-completion.

(This is currently not covered in the documentation, but I do not have the time to update it)

**Comment by mjezzini** [comment]
I have added \bibliography{library} after the \end{document} in main.tex, Now I get the menu selection for the bibliography but it is empty.

> view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : :Tex_FindBibFiles: 
view : Tex_FindBibFiles: found bibliography command in main.tex
view : :Tex_FindBibFiles: bib command from line 16 to line 16
view : :Tex_FindBibFiles: concatenated bib command: "library}"
view : :Tex_FindBibFiles: trying to search through [library]
view : :Tex_FindBibFiles: returning [U:\GitHub\IEEEXtalk\library.bib
]
view : :Tex_SwitchToInsertMode:

The second option opens the .bib file in a new buffer. Here is the log in that case

> view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : +Tex_ScanFileForCite: searching for bibkeys.
view : :Tex_FindBibFiles: 
view : Tex_FindBibFiles: found bibliography command in main.tex
view : :Tex_FindBibFiles: bib command from line 16 to line 16
view : :Tex_FindBibFiles: concatenated bib command: "library}"
view : :Tex_FindBibFiles: trying to search through [library]
view : :Tex_FindBibFiles: returning [U:\GitHub\IEEEXtalk\library.bib
]
view : finding .bib file [main.tex]
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
view : +Tex_SetupCWindow
view : +Tex_SyncPreviewWindow
view : :Tex_SwitchToInsertMode: 
view : Tex_SyncPreviewWindow: got error E32, no matches found, quitting
view : not in quickfix window, quitting
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = Je
view : +Tex_ScanFileForCite: searching for bibkeys.
view : :Tex_FindBibFiles: 
view : Tex_FindBibFiles: found bibliography command in main.tex
view : :Tex_FindBibFiles: bib command from line 16 to line 16
view : :Tex_FindBibFiles: concatenated bib command: "library}"
view : :Tex_FindBibFiles: trying to search through [library]
view : :Tex_FindBibFiles: returning [U:\GitHub\IEEEXtalk\library.bib
]
view : finding .bib file [main.tex]
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
view : +Tex_SetupCWindow
view : +Tex_SyncPreviewWindow
view : :Tex_SwitchToInsertMode: 
view : Tex_SyncPreviewWindow: got error E32, no matches found, quitting
view : not in quickfix window, quitting

**Comment by gerw** [comment]
I am not sure why the first method does not work. I would guess that `bibtools.py` is not able to open your bib-file, but this is hard to check remotely.

If you like, you could fiddle around with the variable `bibfiles` in `Tex_StartCiteCompletion` in `ftplugin/latex-suite/texviewer.vim`, or with the `file` variable in `addfile` in `ftplugin/latex-suite/bibtools.vim`.

**Comment by mjezzini** [comment]
I had changed set autochdir to noautochdir because my "gf" was not working if in a file sitting in a subfolder and that fixed the F9 in my case.
