### ISSUE TITLE
VIM-LaTeX F5 package insertion problem

### ISSUE THREAD

**Issue by KonradHoeffner** [vim-latex/vim-latex#9]
When I insert a package into my preamble in VIM-LaTeX using F5 and select for instance floatflt, instead of \usepackage{floatflt}, I often get the following. How can I solve this?

<++>]{floatflt}"`usepackage[X

Minimal working example:

    \documentclass{article} 
    [here is the cursor when I hit F5]

**Comment by texasflood** [comment]
Can't reproduce on Ubuntu 14.04. What is the output of `:echo g:TeX_package_floatflt` and `:echo g:TeX_package_option_floatflt`?

**Comment by KonradHoeffner** [comment]
The output is the following (it's in German, meaning "undefined variable" and "undefined expression"):

E121: Undefinierte Variable: g:TeX_package_floatflt
E15: ungültiger Ausdruck: g:TeX_package_floatflt

E121: Undefinierte Variable: g:TeX_package_option_floatflt
E15: ungültiger Ausdruck: g:TeX_package_option_floatflt

**Comment by 8leggedunicorn** [comment]
I'm also experiencing the same issue with the amsmath package:

```
%        File: Chapter1.tex
%     Created: Thu May 28 02:00 PM 2015 CDT
% Last Change: Thu May 28 02:00 PM 2015 CDT
%
\documentclass[letter]{article}
Typing amsmath<F5> in input mode:

\usepackage[$icp]{amsmath}<++>
everything is as expected, where $icp is the initial cursor position after hitting <F5>,

Typing <F5> first produces the undesirable effect:
<++>]{amsmath}``usepackage[X
\begin{document}

\end{document}
``` 
with the following options, which are default set for the amsmath package,

```
g:TeX_package_option_amsmath   centertags,tbtags,sumlimits,nosumlimits,intlimits,nointlimits,namelimits,nonamelimits,leqno,reqno,fleqno
```
This setting at least explicitly hasn't been altered since basically the beginning of the available logs,
```
$ git log -S'g:TeX_package_option_amsmath'
commit 3b68fc70bef17556a5228e5bbd9b8beeebb71b3f
Author: Mikolaj Machowski <mikmach@users.sourceforge.net>
Date:   Sat Nov 9 22:52:42 2002 +0000

    first version of amsmath package file
```
Currently I'm using version,
```
commit 0fae2e676cc4beb65ed026639f8419feddb5f4b4
Merge: a9a6dd0 b35939a
Author: Till Maas <opensource@till.name>
Date:   Sat Mar 21 09:38:30 2015 +0100

    Merge pull request #13 from ahmadsalim/master

    Configurable bibliography file generation detection
```

**Comment by texasflood** [comment]
OK, both of you try

```
ls ~/.vim/ftplugin/latex-suite/packages/amsmath
```

and 
```
ls ~/.vim/ftplugin/latex-suite/packages/floatflt
```
respectively.
Both these files should exist. If they do, then for some reason vim latex isn't loading them on startup. If they don't, maybe there was a problem when you were installing vim-latex.

**Comment by texasflood** [comment]
Also, could you give me the output of `:map <F5>` please? Maybe there is a conflict with something else.

**Comment by 8leggedunicorn** [comment]
Yes, as you suggested Tex_FastEnvironmentInsert appears to have something to do with it.  The output for :map <F5> are the two lines:
```
v  <F5>         @<Plug>Tex_FastEnvironmentInsert
n  <F5>         @<Plug>Tex_FastEnvironmentInsert
```

**Comment by 8leggedunicorn** [comment]
So the observed phenomenon appears to be generalizable to inserting a package which contains an options section in insert mode.  That is calling <F5> is failing to expand properly, some examples,
```
<++>]{SIunits}``usepackage[X
<++>]{amsmath}``usepackage[X
<++>]{floatflt}``usepackage[X
<++>]{geometry}``usepackage[X
```

**Comment by 8leggedunicorn** [comment]
Went back to right before there were changes made to packages.vim but the issue persists, and similarly back to mid-2012 and again error persists,

```
$ git status
HEAD detached at d2771a2
nothing to commit, working directory clean
```
So possibly changes with Vim upstream.  Next step will be to try older versions of Vim to see if the issue is reproduced.

**Comment by texasflood** [comment]
Perhaps you should try running vim in verbose mode `vim -V` or debug a particular function to be debugged `debug call FunctionName(arg)` (http://inlehmansterms.net/2014/10/31/debugging-vim/)? Unfortunately I don't think I can help as I am not facing the error myself. What OS are you on?

**Comment by 8leggedunicorn** [comment]
I've tested and reproduced this issue on Ubuntu 15.04, as well as Windows 8.1.  Both are using some variant of Vim 7.4, where I've installed Vim-Latex through Pathogen.  Currently I've changed the line to,

```
let retVal = retVal.'\usepackage[]{'.packname.'}'."\<CR>"
```
for the moment so that this issue doesn't present itself but of course it doesn't provide the same functionality,
```
let retVal = retVal.'\usepackage[<++>]{'.packname.'}<++>'
```
does, and points to other potential incompatibilities up ahead.

**Comment by texasflood** [comment]
OK, it turns out I was misunderstanding the problem the whole time. I always type the package name and then press <kbd>F5</kbd> so I never faced the issue. But when I press <kbd>F5</kbd> on an empty line in the preamble and insert `SIunits` for example, then I get the same issue.

**Comment by dfshan** [comment]
I also fix the bug, it only needs one line change.
https://github.com/dfshan/vim-latex

**Comment by gerw** [comment]
I think I have found a workaround for this bug(?): Try to insert a `redraw` after the line 460 (`let inp = input(a:dialog)`) in the function `Tex_ChooseFromPrompt` (located in `ftplugin/latex-suite/main.vim`).

This fixes this bug for me.
