### ISSUE TITLE
Set NoSpell for cleverref

### ISSUE THREAD

**Issue by mjezzini** [vim-latex/vim-latex#90]
Hello,

I would like that vim-latex do not highlight spell mistakes inside the \cref{} or \Cref{} as it already does it for \ref{}, \cite{} and \input{}. Those commands are provided by the cleveref package.

Thanks

**Comment by gerw** [comment]
The syntax highlighting is not provided by the latex-suite. Either, you contact the maintainer of the highlighting, or use a workaround like https://github.com/gerw/vim-tex-syntax/blob/4f58f1122a44dbc4bf86f09a1faadf5ee0390e9b/after/syntax/tex/cleveref.vim.

**Comment by mjezzini** [comment]
Great! That was very useful! For some reason, the files in my after folder are not loaded automatically. After saving the file in the link you provided,  I had to add `set runtimepath+=U:/VIM/vimfiles/after` at the very end of my vimrc to make it work.
