### ISSUE TITLE
SumatraPDF inverse searching opens a new gvim session in Windows

### ISSUE THREAD

**Issue by mjezzini** [vim-latex/vim-latex#91]
Hello, 

I configured SumatraPDF with 

> "C:\Program Files (x86)\Vim\vim80\gvim" -c ":RemoteOpen +%l %f"

as stated in the documentation [here](http://vim-latex.sourceforge.net/documentation/latex-suite/inverse-searching.html). The problem is everytime I do an inverse search a new gvim terminal gets open instead of reusing the session. 

I changed the configuration in SumatraPDF to 

> "C:\Program Files (x86)\Vim\vim80\gvim" --remote-silent +%l %f 

and it is working for me. 

This might not be a problem if you prefer to get a new gvim session, but someone else might also prefer to reuse the instance, so I am putting this comment here for somebody looking for the option. Maybe a note in the documentation could be useful.

**Comment by gerw** [comment]
Your second approach does not work if you have multiple instances of `gvim` running, since the file might be opened in the wrong `gvim` session.

The first approach, however, should open a new `gvim` window, which is closed shortly after, and the file is loaded in the correct `gvim` session.

Can you enable the logging of latex-suite and show the log-file after an failed attempt? Note that you have to find the correct log-file (in the working directory of SumatraPDF, or you use an absolute path, i.e.,`let g:Tex_DebugLog = "C:\vim-latex-suite.log").

**Comment by mjezzini** [comment]
I have set SumatraPDF with 
>"C:\Program Files (x86)\Vim\vim80\gvim" -c ":RemoteOpen +%l %f"

This is the log resutls
>proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [U:\GitHub\IEEEXtalk\main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
SyntaxFolds : Finished folding in   0.000092 seconds.
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
pack : :Tex_pack_updateall: sview U:\GitHub\IEEEXtalk\main.tex
pack : +Tex_ScanForPackages
pack : :Tex_ScanForPackages: Begining scans in [U:\GitHub\IEEEXtalk\main.tex], beginline = 4
pack : :Tex_ScanForPackages: beginning scan for \usepackage lines
pack : :Tex_ScanForPackages: End scan \usepackage, detected packages = 
pack : :Tex_ScanForPackages: Beginning scan for \newcommand's
pack : :Tex_ScanForPackages: Beginning scan for \newenvironment's
pack : -Tex_ScanForPackages
pack : :Tex_pack_updateall: detected [] in first run
pack : :Tex_pack_updateall: throwing LatexSuiteScannedPackages event
pack : -Tex_pack_updateall
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [U:\GitHub\IEEEXtalk\main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall

I get a new gvim session instead of reusing the current one

**Comment by gerw** [comment]
This does not contain any useful information. Does `:echo has('clientserver')` gives `1`?

To find the error, you could try the following:
* Open a file in vim, lets say `C:\bar.tex`.
* Open a new vim with a new tex file (to load latex suite), preferably in a different directory, e.g., `C:\foo\foo.tex`. In this vim, call `:RemoteOpen C:\bar.tex` (or, `:RemoteOpen C:/bar.tex`, I am not sure about the slashes in windows). This second instance of vim should be closed, and the first one should receive focus.
* Check the log file of the second vim in `C:\foo\vim-latex-suite.log`.

**Comment by mjezzini** [comment]
`:echo has('clientserver')` is `1`

The bar.tex, foo.tex exercise worked as expected. Here is the log
> 
proj : texproject.vim: catching LatexSuiteFileType event
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
SyntaxFolds : Finished folding in   0.000177 seconds.
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
pack : :Tex_pack_updateall: split
pack : +Tex_ScanForPackages
pack : :Tex_ScanForPackages: Begining scans in [foo\foo.tex], beginline = 0
pack : :Tex_ScanForPackages: beginning scan for \usepackage lines
pack : :Tex_ScanForPackages: End scan \usepackage, detected packages = 
pack : :Tex_ScanForPackages: Beginning scan for \newcommand's
pack : :Tex_ScanForPackages: Beginning scan for \newenvironment's
pack : -Tex_ScanForPackages
pack : :Tex_pack_updateall: detected [] in first run
pack : :Tex_pack_updateall: throwing LatexSuiteScannedPackages event
pack : -Tex_pack_updateall
proj : texproject.vim: catching LatexSuiteFileType event
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
RemoteOpen : linenum = 1, filename = U:\bar.tex

**Comment by gerw** [comment]
Now I see why there is no debug information from the `RemoteOpen` command (the latex suite is not loaded yet, hence there is no debugging functionality). Can you copy the debug code from  https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/main.vim#L182 -- https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/main.vim#L213 to the beginning of `plugin/remoteOpen.vim`? Then, your log should contain lines like
````
linenum = 3, filename = barfoo: RemoteOpen
````
see https://github.com/vim-latex/vim-latex/blob/master/plugin/remoteOpen.vim#L58

**Comment by mjezzini** [comment]
I did, and this is what I get:

> proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [U:\GitHub\IEEE_LTCC_Transition\main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
SyntaxFolds : Finished folding in   0.000153 seconds.
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : compiler/tex.vim: sourcing this file
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
pack : :Tex_pack_updateall: sview U:\GitHub\IEEE_LTCC_Transition\main.tex
pack : +Tex_ScanForPackages
pack : :Tex_ScanForPackages: Begining scans in [U:\GitHub\IEEE_LTCC_Transition\main.tex], beginline = 4
pack : :Tex_ScanForPackages: beginning scan for \usepackage lines
pack : :Tex_ScanForPackages: End scan \usepackage, detected packages = 
pack : :Tex_ScanForPackages: Beginning scan for \newcommand's
pack : :Tex_ScanForPackages: Beginning scan for \newenvironment's
pack : -Tex_ScanForPackages
pack : :Tex_pack_updateall: detected [] in first run
pack : :Tex_pack_updateall: throwing LatexSuiteScannedPackages event
pack : -Tex_pack_updateall
proj : texproject.vim: catching LatexSuiteFileType event
proj : Tex_ProjectLoad: sourcing [U:\GitHub\IEEE_LTCC_Transition\main.tex.latexmain]
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateal

No `<linenum = 3, filename = barfoo: RemoteOpen>` so not sure what is happening

One thing that I just noticed, is that RemoteOpen seems to work fine with a project that is a single file, not using `\input{}`. But my project has in the main.tex `\input{sec/section}`, it opens a second gvim session.

**Comment by gerw** [comment]
Your last paragraph should be the point. `RemoteOpen` only looks for a vim in which the precise tex file is already opened. You could try to open `sec/section.tex` in your vim _before_ issuing the inverse search. Does this work?

**Comment by mjezzini** [comment]
Yes, if I have the target file (e.g. `sec/section.tex`) already open it does change the focus to that right buffer.

**Comment by gerw** [comment]
There is no possibility how latex-suite should know in which gvim session your tex-file should be opened.

In linux, I use something like the following:
- Set a shell-local environment variable `GVIMSERVER`
- Open the gvim with `GVIMSERVER` as `servername`
- The viewer calls a bash script `gvim_wrapper`:
```
#!/bin/bash

# Calls gvim to show a specific line in a tex-file
# Prerequirement: - gvim should be started with "--servername $texfile"
#                 - ENV variable GVIMSERVER is set to the main tex file

texfile=$1
line=$2
column=$3

if [[ "x$GVIMSERVER" != "x" ]]; then
        servername="$GVIMSERVER"
else
        # Fallback...
        servername="$(basename $1)"
fi

# Call vim to edit the file at the given line
gvim --servername "$servername" --remote +${line} "$texfile"
# Open the folds under the cursor:
gvim --servername "$servername" --remote-send zO
```
- This will open the tex file in the correct gvim session.
