### ISSUE TITLE
Compiling Error when there is a Makefile in your latex project folder

### ISSUE THREAD

**Issue by jiayouwyhit** [vim-latex/vim-latex#95]
If there is a Makefile in your latex project folder, you will get the following error when you try to compile the tex file.

<img width="399" alt="screen shot 2017-06-09 at 4 51 31 pm" src="https://user-images.githubusercontent.com/6230202/26968282-0dee5576-4d34-11e7-83e3-139cea3a9c1b.png">

The solution is:
**Just simply remove or rename the Makefile to another name to disable it**.

**Comment by gerw** [comment]
This can be controlled by the variable `Tex_UseMakefile`, see http://vim-latex.sourceforge.net/documentation/latex-suite/customizing-compiling.html#Tex_UseMakefile.

Does this resolve your problem?

**Comment by jiayouwyhit** [comment]
Thanks a lot for your suggestion, @gerw . My previous solution is to just simply remove the makefile under my folder, but your solution is much better!
